### ISSUE TITLE
Demo Page infinite loop render when url contains path subroutes

### ISSUE THREAD

**Issue by DubiEX** [tradingview/charting-library-examples#1]
Hi,

I found a really weird bug, I cloned the repo and copied the required folders to a public folder, everything is working fine, but when I put `/something/` in the url then page seems to loop itself forever. Here's how it looks.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35936100/36355736-02806f22-14e8-11e8-814e-0ad3b1c5ca63.gif)

I put the alert inside the bundle file to show that the whole script is called multiple times when there's subroute in url. here's where I put it.

![alertishere](https://user-images.githubusercontent.com/35936100/36355726-d779a7c6-14e7-11e8-860a-b5e0fa4b5dc3.png)

I'm using the latest tradingView lib version (1.12) I didn't make any modifications other than putting that `alert` in bundle. Problem is also present on Firefox. I'm developing on Windows machine.

Would like to know how to fix that or any workaround because my page depends on what tokens are in url to determine what data should chart show and this issue prevents me from integrating TradingView.

I also found the same behaviour using fresh `create-react-app` app [HERE](https://github.com/tradingview/charting_library/issues/2503)

**Comment by ezhukovskiy** [comment]
Hi,
yes, it is a bug in `create-react-app` that returns the default page if an incorrect URL is entered.
If you use another HTTP server than `create-react-app`, you won't have this error.
If you know how to fix it, please make a PR.
