### ISSUE TITLE
 Cannot find module '../../../public/charting_library/charting_library.min'.

### ISSUE THREAD

**Issue by qizf7** [tradingview/charting-library-examples#10]
Failed to compile
/Users/alibaba/Downloads/charting-library-examples-master/react-example/src/components/TVChartContainer/index.tsx
(6,8): Cannot find module '../../../public/charting_library/charting_library.min'.
This error occurred during the build time and cannot be dismissed.

**Comment by timocov** [comment]
Did you 3 step from https://github.com/tradingview/charting-library-examples/tree/master/react-example#how-to-start?
