### ISSUE TITLE
Not able to load chart in react-native

### ISSUE THREAD

**Issue by loforex** [tradingview/charting-library-examples#109]
I just download repositories from your github account.

https://github.com/tradingview/charting_library

https://github.com/tradingview/charting-library-examples

above first repo I have tried to run first in browser and its working fine.
see screen shot below.

![image](https://user-images.githubusercontent.com/18213476/59509945-14834600-8ed0-11e9-8604-9aef55a9d701.png)

when I tried to add this same thing in my react native app. it is not getting load and it gives me below screen.

![image](https://user-images.githubusercontent.com/18213476/59509967-249b2580-8ed0-11e9-86cd-a445111b17d9.png)

App.js

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import React, { Component } from 'react';
import { Platform } from 'react-native';
import { WebView } from 'react-native-webview';

// Currently only iOS available
const isAndroid = Platform.OS === 'android';

export default class App extends Component {
    render() {
        return (
            <WebView
                bounces={false}
                source={{
                    uri: isAndroid
                        ? 'file:///android_asset/charting_library/index.html'
                        : 'index.html',
                    baseUrl: ''
                }}
                onShouldStartLoadWithRequest={request => {
                    return true;
                }}
                originWhitelist={['*']}
                javaScriptEnabled={true}
                useWebKit={true}
            />
        );
    }
}
`

Package.Json

`{
  "name": "Example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-webview": "^5.3.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.4.0",
    "jest": "24.4.0",
    "metro-react-native-babel-preset": "0.53.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}`

Here I have added charting_library in android folder.

![image](https://user-images.githubusercontent.com/18213476/59510025-498f9880-8ed0-11e9-8831-0454f8bb907a.png)

Note:: All code is from your above mentioned repository. more information you can get from https://github.com/tradingview/charting-library-examples.

let me know if you want more information on it.

**Comment by timocov** [comment]
@makedonsky94 can you please take a look?

**Comment by makedonsky94** [comment]
Hi! Unfortunately, there is no working sample for Android right now. Currently, the sample [React-Native](https://github.com/tradingview/charting-library-examples/tree/master/react-native) is for iOS only.

**Comment by loforex** [comment]
@makedonsky94  Okay. one more thing how we can change symbol data in after integration?
any example is ready for that?

I want chart with my API

**Comment by loforex** [comment]
we are using vertax API

**Comment by loforex** [comment]
There ? Please reply

**Comment by knap1930** [comment]
@makedonsky94 is there no working sample for Android because it won't work, or just because no one has created one yet?

I am trying to get it to work, and get the following error
![image](https://user-images.githubusercontent.com/6470136/60390740-42e94f80-9a92-11e9-9037-67e2653f03da.png)

`
2019-06-29 17:23:37.756 6244-8426/com.aobot W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 1):
    Error: Could not open URL 'file:///android_asset/charting_library/charting_library/static/en-tv-chart.e6c523133ea801233691.html#symbol=AAPL&interval=D&widgetbar=%7B%22details%22%3Afalse%2C%22watchlist%22%3Afalse%2C%22watchlist_settings%22%3A%7B%22default_symbols%22%3A%5B%5D%7D%7D&timeFrames=%5B%7B%22text%22%3A%225y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%221y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%226m%22%2C%22resolution%22%3A%22120%22%7D%2C%7B%22text%22%3A%223m%22%2C%22resolution%22%3A%2260%22%7D%2C%7B%22text%22%3A%221m%22%2C%22resolution%22%3A%2230%22%7D%2C%7B%22text%22%3A%225d%22%2C%22resolution%22%3A%225%22%7D%2C%7B%22text%22%3A%221d%22%2C%22resolution%22%3A%221%22%7D%5D&locale=en&uid=tradingview_c9999&clientId=tradingview.com&userId=public_user_id&chartsStorageUrl=http%3A%2F%2Fsaveload.tradingview.com&chartsStorageVer=1.1&debug=false&timezone=Etc%2FUTC': file:///android_asset/charting_library/charting_library/static/en-tv-chart.e6c523133ea801233691.html#symbol=AAPL&interval=D&widgetbar=%7B%22details%22%3Afalse%2C%22watchlist%22%3Afalse%2C%22watchlist_settings%22%3A%7B%22default_symbols%22%3A%5B%5D%7D%7D&timeFrames=%5B%7B%22text%22%3A%225y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%221y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%226m%22%2C%22resolution%22%3A%22120%22%7D%2C%7B%22text%22%3A%223m%22%2C%22resolution%22%3A%2260%22%7D%2C%7B%22text%22%3A%221m%22%2C%22resolution%22%3A%2230%22%7D%2C%7B%22text%22%3A%225d%22%2C%22resolution%22%3A%225%22%7D%2C%7B%22text%22%3A%221d%22%2C%22resolution%22%3A%221%22%7D%5D&locale=en&uid=tradingview_c9999&clientId=tradingview.com&userId=public_user_id&chartsStorageUrl=http%3A%2F%2Fsaveload.tradingview.com&chartsStorageVer=1.1&debug=false&timezone=Etc%2FUTC exposed beyond app through Intent.getData()
    createErrorFromErrorData@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2108:26
    http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2060:51
    __invokeCallback@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2627:23
    http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2358:34
    __guard@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2531:15
    invokeCallbackAndReturnFlushedQueue@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2357:21
    invokeCallbackAndReturnFlushedQueue@[native code]
`

**Comment by knap1930** [comment]
I got past this issue by setting
```
originWhitelist={['file://*', 'https://*', 'http://*']}
```

however now I see a blank page, which I am fairly sure is coming from this code
```
<script>if(window===window.parent){location.href="about:blank"};</script>
```
in en-tv-chart.e6c523133ea801233691.html because of this issue

https://github.com/react-native-community/react-native-webview/issues/560

**Comment by timocov** [comment]
> how we can change symbol data in after integration?
> any example is ready for that?

It's not about examples, please create another issue in charting_library repo.

**Comment by nonotest** [comment]
tv is working fine on android when loading from a website (eg not static assets)

**Comment by Rishabhai** [comment]
> tv is working fine on android when loading from a website (eg not static assets)

In that case , all JS API or UDF api is implemented in backend and gives response as an html file which you show using webview ?
I am trying you implement JSApi in react native on android , i am getting error while fetching static tradingview library files.

**Comment by Harsha192** [comment]
I'm getting a blank screen while loading charting_library/index.html file in a webview. 
![image](https://user-images.githubusercontent.com/19972882/193032259-9360deef-8b0f-4076-8932-80ef1ec5ce30.png)
Does anyone have idea what is the issue here ?

**Comment by Vashu473** [comment]
Just degrade your webView version , It will resolve your problem
