### ISSUE TITLE
How do I detect the creation of a trendline?

### ISSUE THREAD

**Issue by ekkis** [tradingview/charting-library-examples#11]
I’ve looked carefully through the developer documentation for the library but cannot find a proper way to hook onto the creation of a trendline on the graph

I see `onDataLoaded()`, `onSymbolChanged()`, `onIntervalChange()` and `dataReady()`, none of which would trigger when the user drops a trendline on the chart.  the best I seem to find is the crossHairMoved() which fires every time the cursor moves.  I can use that to go find the trendline (using the `getAllShapes()` method) but that's both costly and stupid

what is the proper way?

**Comment by ezhukovskiy** [comment]
Hi,
please ask all your questions in the charting_library repo.

**Comment by ekkis** [comment]
there's no such repo.  here are the repositories listed under TradingView:

tv-pylint-translations-rule
charting-library-examples
tradingview
dynamic-dual-import-webpack-plugin
yahoo_datafeed
saveload_backend
tradingview.github.io
webpack-uglify-parallel
tv-polyfill
react-redux-ts-demo
css-file-rules-webpack-separator

**Comment by timocov** [comment]
This is private repo and [request an access to this repository](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/).
