### ISSUE TITLE
Uncaught TypeError: r.contentWindow.widgetReady is not a function     at HTMLIFrameElement.t (charting_library.min.js:2)

### ISSUE THREAD

**Issue by dengjiexiao** [tradingview/charting-library-examples#110]

**Comment by eugene-korobko** [comment]
Hello!
Could you please provide more details about your way of integrating charting library?

**Comment by lacksfish** [comment]
For me, the React app was hosted on a subfolder on my domain, so somewhere in your code where you do something similar to:

```
static defaultProps = {
        ...
        libraryPath: '/INSERT_SUBFOLDER_HERE/charting_library/',
        chartsStorageUrl: 'https://saveload.tradingview.com',
        chartsStorageApiVersion: '1.1',
        clientId: 'test',
        ...
    };
```

You want to make sure that `libraryPath` is including the subfolder in the URL, that fixed it for me :+1:

**Comment by lacksfish** [comment]
Also, apart from that, double check the couple setup steps from tradingview here:

https://github.com/tradingview/charting-library-examples/tree/master/react-javascript#how-to-start

**Comment by Ale-cc** [comment]
Just remove
 `window.TradingView.onready(() => {
   });`

TradingView runs.

**Comment by Ferigit** [comment]
@Ale-cc hi, did you solve thru this way!? it does not work for me!

**Comment by Viktor19931** [comment]
@Ale-cc any updates ? I got save error in prod env
