### ISSUE TITLE
Next.js with TradingView

### ISSUE THREAD

**Issue by PTBKoo** [tradingview/charting-library-examples#111]
Ive followed this example to try and integrate TV with Next.js
https://github.com/tradingview/charting-library-examples/tree/master/react-javascript

First error I was getting was window was undefined so I added a check to import only when window was defined and was getting a new error: TypeError: Cannot set property 'TradingView' of undefined

Used this to help:
https://github.com/zeit/next.js/wiki/FAQ

Link to main code: https://github.com/PTBKoo/nexttv/blob/master/pages/index.js

0. Clone the repo @ https://github.com/PTBKoo/nexttv
1. Add charting_library and datafeeds to static folder
2. npm install
3. npm run dev

<img width="1016" alt="Screen Shot 2019-06-18 at 4 48 32 PM" src="https://user-images.githubusercontent.com/29348754/59727098-27a45780-91e9-11e9-9327-11c76530223f.png">

**Comment by timocov** [comment]
See #30

**Comment by geun** [comment]
I make PR for nextjs

**Comment by afsanefda** [comment]
do you have an example to help me? I even can not get the library through this link https://github.com/tradingview/charting_library/
it is 404!

**Comment by afsanefda** [comment]
> @timocov I make PR for nextjs.

I need help if you had the experience using trading view charts in nextjs. Could you please help me?

**Comment by geun** [comment]
@afsanefda  you should authorize to access https://github.com/tradingview/charting_library 

You can apply it
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
