### ISSUE TITLE
Example where datafeeds is placed under the src folder (react-javascript)

### ISSUE THREAD

**Issue by farablanco** [tradingview/charting-library-examples#114]
- **Framework/library:**  ReactJS

Hi,

I want to access the datafeeds builds from src folder instead of public.
Can anyone show how that is done?
Thanks,

Fara

**Comment by timocov** [comment]
> from src folder instead of public.

What do you mean?

**Comment by farablanco** [comment]
Didn't want to place datafeeds in public since it does not get built.
But figured it out.
Thanks.
