### ISSUE TITLE
Unable to create multi line indicator.

### ISSUE THREAD

**Issue by yaseenayahya** [tradingview/charting-library-examples#119]
how can i change color of line on my condition.

I am trying to set plot brush in this this method. Is this Possible ?

 this.main = function(context, inputCallback) {
var b = 0;
var plotbrush = b == 0 ? "green" : "black";

changePlotBrush(plotbrush); //contains any this type of method
}

**Comment by timocov** [comment]
@yaseenayahya please stop create unrelated to this repo issues. If you want to get help with the charting library - please create an issue in https://github.com/tradingview/charting_library repo (I've moved 2 previously created issues https://github.com/tradingview/charting_library/issues/4201 https://github.com/tradingview/charting-library-examples/issues/118).

**Comment by yaseenayahya** [comment]
unable to access   https://github.com/tradingview/charting_library having
404. can you help me authenticate this repo..??

**Comment by timocov** [comment]
You need to request an access via https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/.
