### ISSUE TITLE
Is there an example of the react-js version now?

### ISSUE THREAD

**Issue by zhangyu0218** [tradingview/charting-library-examples#12]
Is there an example of the react-js version now?

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/tree/master/react-javascript

It is `react-typescript` example written in JavaScript (I just stripped all types from code and remove some TypeScript's stuff).

**Comment by zhangyu0218** [comment]
Why did I introduce 'charting_library. min.js' on my own react project with the following error?

![image](https://user-images.githubusercontent.com/33249149/39622642-9a6e1290-4fc5-11e8-879c-96268aaf1cb6.png)

Do I need to modify what is in my project?

**Comment by timocov** [comment]
It is related to your project structure and `react-scripts` - they does not allow to import files outside `src` folder.

To fix it you need to move `charting_library` inside `src` folder or remove `react-scripts` and use own webpack configs.

**Comment by zhangyu0218** [comment]
I moved charting_library to the src directory, but there are new problems

![image](https://user-images.githubusercontent.com/33249149/39624146-c81698b6-4fca-11e8-9951-6850b3e2770d.png)

**Comment by timocov** [comment]
I'm not sure now you can fix it. Possible you need to search how `react-scripts` works.

I prefer to use own webpack config and control what I expect from building the application. In examples we use `react-scripts` to decrease other stuffs which are not related to example itself.

But anyway seems that our examples works fine.

@everget could you please take a look?

**Comment by timocov** [comment]
The reason of this behavior is importing `charting_library.min.js` file instead of using global variables to create charting library widget (and import is preferred way to create charting library widget).

I guess we need to "fix" our examples to use importing instead of using global variables (where it is possible), but I am not sure whether we can do it with `react-scripts`.

**Comment by zhangyu0218** [comment]
Can you provide a contact information, such as facebook, I still have some questions to ask you, for example: how to connect my data to tradingView

**Comment by timocov** [comment]
> how to connect my data to tradingView

For such questions you can create an issue in charting_library repo.

**Comment by zhangyu0218** [comment]
Why do I get 404 when I visit? 
Is it because my github account did not pass tradingView audit?

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/tree/master/react-javascript#how-to-start

> If you get 404 then you need to request an access to this repository.

**Comment by zhangyu0218** [comment]
OK Thank you for solving my problem

**Comment by timocov** [comment]
@zhangyu0218 If you have no access to the repo, where did you find `charting_library.min.js` file?

**Comment by alex-solovev** [comment]
> @zhangyu0218 If you have no access to the repo, where did you find `charting_library.min.js` file?

LOL
