### ISSUE TITLE
'DEFAULT_VALUE is not defined' In VueJS SPA

### ISSUE THREAD

**Issue by yuriygeorge** [tradingview/charting-library-examples#126]
'DEFAULT_VALUE is not defined' Error shows when enter on page with TradingView charts. But if refresh full page (F5), all works fine.

**Comment by timocov** [comment]
Do you have repro code? It would be very useful to help with this issue.

**Comment by yuriygeorge** [comment]
Sorry, but I cannot publish this code.

Try to make reproduce this situation on new project

**Comment by yuriygeorge** [comment]
I found some reason

When I add datafeed url from example ('https://demo_feed.tradingview.com') all works. But with our API url situation repeats:

> 'DEFAULT_VALUE is not defined' Error shows when enter on page with TradingView charts. But if refresh full page (F5), all works fine.

I think problem in realization of GET '/config' request

![Screenshot from 2019-08-28 12-53-11](https://user-images.githubusercontent.com/4934760/63845768-3189ca00-c993-11e9-9fb4-984cccba5eea.png)

**Comment by yuriygeorge** [comment]
I resolve this - problem was in my routing and internal logic.
