### ISSUE TITLE
Ios charting_library not working

### ISSUE THREAD

**Issue by tahlilaty** [tradingview/charting-library-examples#129]
I have followed and ran successfully android example but ios the library is not working as i followed the instructions of the example but noting is loaded just a blank screen. Is the library for ios is different then android and library that i used in android does not work on ios example

**Comment by timocov** [comment]
@RomanGal can you please take a look?

**Comment by tahlilaty** [comment]
Dear Team,


Mr. Furqan (nfs.awam@gmail<mailto:nfs.awam@gmail>) is our IOS developer and we need some assistance regarding implementation of technical charts in IOS as we have successfully implemented in android.
Please assist.


Thanks

**Comment by greenJVS** [comment]
@tahlilaty What options do you use when you add library files to a Xcode project? Try setting the value "Create folder references" for the added folders.
If this does not help, please show your initialization code and WKWebView instance setup code.

**Comment by tahlilaty** [comment]
I  simply added this library https://github.com/tradingview/charting_library  folder in the sample downloaded from here and ran the sample but no chart shown just blank screen. Below is given the code of sample

   override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        let frame = UIScreen.main.bounds;
        
        let configuration = WKWebViewConfiguration()
        configuration.preferences.setValue(true, forKey: "allowFileAccessFromFileURLs")
        configuration.preferences.javaScriptEnabled = true
        
        let urlRaw = Bundle.main.url(forResource: "index", withExtension: "html")
        
        let webView = WKWebView(frame: frame, configuration: configuration)
        guard let url = urlRaw else {
            print("No file at url")
            return
        }
        webView.uiDelegate = self

        webView.loadFileURL(url, allowingReadAccessTo: url)
        
        view.addSubview(webView)
    }

**Comment by greenJVS** [comment]
@tahlilaty is console output empty?

**Comment by tahlilaty** [comment]
Yes console is empty it is picking library html page but not showing any thing but same library is working on android sample by just adding

**Comment by greenJVS** [comment]
@tahlilaty What version of Xcode and iOS are you using? Are you running the program on a device or simulator?

**Comment by Ssunnyy** [comment]
@greenJVS 
I am an IOS developer
I use the charging library applied by the company to put it into IOS swift demo and run the white screen on the iPhone without any display. Please ask how to integrate to make the program run normally. Thank you

<img width="730" alt="截屏2019-12-05下午3 12 57" src="https://user-images.githubusercontent.com/7019575/70213222-cc085f00-1773-11ea-80b8-06df1faa84db.png">
<img width="217" alt="截屏2019-12-05下午3 13 25" src="https://user-images.githubusercontent.com/7019575/70213228-cf034f80-1773-11ea-8441-da850839f963.png">

**Comment by greenJVS** [comment]
@Ssunnyy,
When you add a library to your project, you must select “Create folder references” for the added folders. This is important because the library contains files with the same name, but in different folders, so the “Create folder references” option adds files to your application bundle with the same folder structure as in the library.
Note that the added folders should be blue, not yellow.
![Screenshot 2019-12-05 at 10 52 28](https://user-images.githubusercontent.com/36850517/70215573-cfd5ba80-174e-11ea-8ea4-2a92b42b5143.png)
![Screenshot 2019-12-05 at 10 50 55](https://user-images.githubusercontent.com/36850517/70215574-cfd5ba80-174e-11ea-9ce1-2407dbb661d6.png)

**Comment by Ssunnyy** [comment]
@greenJVS Thank you very much. According to your prompt, it can be displayed correctly。

**Comment by timocov** [comment]
Looks like this issue could be closed due #155. If you have any questions - feel free to re-open/comment it/create another issue.
