### ISSUE TITLE
Дайте доступ плз 

### ISSUE THREAD

**Issue by alexejn** [tradingview/charting-library-examples#140]
https://github.com/tradingview/charting_library не могу открыть
хочу запустить пример на свифте, но доступа к библиотеке нету ((

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/tree/master/ios-swift#how-to-start

> If you get 404 then you need to request an access to this repository.

https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
