### ISSUE TITLE
window.TradingView.onready is not a function

### ISSUE THREAD

**Issue by revanth666** [tradingview/charting-library-examples#145]
TypeError: window.TradingView.onready is not a function TVChartContainer.componentDidMount 

/TradeViewChart/tradingview-js-api-tutorial-master/tradingview-js-api-tutorial-master/part1/src/components/TVChartContainer/index.jsx:58

**Comment by revanth666** [comment]
Can any one please tell how to pass own data to charting library and where to pass

**Comment by elukonina** [comment]
> Method `onready` was removed. You can use `window.addEventListener('DOMContentLoaded', callback, false)` instead.

You can see [Breaking-Changes](https://github.com/tradingview/charting_library/wiki/Breaking-Changes#version-114)

**Comment by SunilKumarHurkat** [comment]
TypeError: window.TradingView.onready is not a function TVChartContainer.componentDidMount

/TradeViewChart/tradingview-js-api-tutorial-master/tradingview-js-api-tutorial-master/part1/src/components/TVChartContainer/index.jsx:58
