### ISSUE TITLE
Creating Custom Indicator On Tradingview  v1.14

### ISSUE THREAD

**Issue by norasteria** [tradingview/charting-library-examples#148]
Hi all, 

I'm new on using Tradingview library, nowdays, I have a project for trading chart using ReactJs and Tradingview v1.14. I have an issue about creating custom indicators. Based on example from one of articles I found ([https://www.jianshu.com/p/2b49b75cada0](https://www.jianshu.com/p/2b49b75cada0)) I succeed created BarColor indicator, but for creating Equity indicator (from that article), the indicator not created. Is that because of PineJS is not defined before? 

Here is my code for creating Equity indicator
![Screenshot from 2019-11-29 15-38-58](https://user-images.githubusercontent.com/24922181/69855575-5fe2b280-12be-11ea-9d18-904dc7048ab4.png)

and here's my code for react component:
![Screenshot from 2019-11-29 16-12-38](https://user-images.githubusercontent.com/24922181/69857814-44c67180-12c3-11ea-9d13-c69deed32244.png)

And put the file contains custom indicators configuration inside `public/` folder
![Screenshot from 2019-11-29 16-07-37](https://user-images.githubusercontent.com/24922181/69857343-67a45600-12c2-11ea-809e-dc79493e05db.png)

What should I do to get that PineJS object ? And another issue is the documentation of creating custom indicators configuration. Anyone here has reference about the complete documentation?
Thanks

**Comment by eugene-korobko** [comment]
Hello!

Could you please clarify what do you mean as ' the indicator not created' ? Do you have any errors in console?

**Comment by norasteria** [comment]
> Hello!
> 
> Could you please clarify what do you mean as ' the indicator not created' ? Do you have any errors in console?

The custom indicator didn't appear at indicator window. After I turning debug as true, it showed this:

![Screenshot from 2019-11-30 06-15-45](https://user-images.githubusercontent.com/24922181/69892536-1aaf9680-1339-11ea-8f3b-7e5cc17b66cb.png)

**Comment by norasteria** [comment]
> > Hello!
> > Could you please clarify what do you mean as ' the indicator not created' ? Do you have any errors in console?
> 
> The custom indicator didn't appear at indicator window. After I turning debug as true, it showed this:
> 
> ![Screenshot from 2019-11-30 06-15-45](https://user-images.githubusercontent.com/24922181/69892536-1aaf9680-1339-11ea-8f3b-7e5cc17b66cb.png)

Well, It solved guys. We just to change the symbol to the ticker from PineJS, like so : 
```

    constructor: function() {
      this.init = function(context, inputCallback) {
        this._context = context;
        this._input = inputCallback;

        this._context.new_sym(
          PineJS.Std.ticker(this._context),
          PineJS.Std.period(this._context),
          PineJS.Std.period(this._context)
        );
      };

      this.main = function(context, inputCallback) {
        this._context = context;
        this._input = inputCallback;

        this._context.select_sym(1);
        var v = PineJS.Std.close(this._context);
        return [v];
      };
    }
```

Thanks .

**Comment by timocov** [comment]
This issue should be in `charting_library` repo.
