### ISSUE TITLE
React-native: Example not working with react-native-webview@7

### ISSUE THREAD

**Issue by ngocdv-namitrade** [tradingview/charting-library-examples#149]
- **Framework/library:** React-native

From react-native-webview v7, the example does not work anymore.
It shows only blank screen. v5 and v6 work fine.

**Comment by ngocdv-namitrade** [comment]
Ok for any others who encountered the same problem like me, we need a little patch to react-native-webview WKWebView
`[_webView.configuration.preferences setValue:@TRUE forKey:@"allowFileAccessFromFileURLs"];`

**Comment by shoebhoney** [comment]
@ngocdv-namitrade what was your **react-native** version? I am also facing same issue.
Its not working in `"react-native": "0.59.8"`
