### ISSUE TITLE
react-javascript example does not work in production.

### ISSUE THREAD

**Issue by anboia** [tradingview/charting-library-examples#15]
When I run `yarn build` followed by `serve -s build` to start the example in production mode, the example does not work. Here is the error that shows up:

![screen shot 2018-05-08 at 1 35 15 pm](https://user-images.githubusercontent.com/4477665/39778759-95471c6a-52dd-11e8-9ba1-c3d9e5765fc5.png)

There is no error when simply running `yarn start`.

The error seems to be similar to #1

**Comment by timocov** [comment]
Do you copy `charting_library` and `datafeed` folders to `react-javascript/public` folder as described [here](https://github.com/tradingview/charting-library-examples/tree/master/react-javascript#how-to-start)?

**Comment by anboia** [comment]
Yes, I did. As I mentioned, there is no error when running in development mode (`yarn start`), the TradeView works perfectly.

**Comment by timocov** [comment]
I have tried to reproduce it with latest `master` and it works fine.

**Comment by ukrit-himakoon** [comment]
We got the same issue today @anboia @timocov Not sure how you solve this?

**Comment by timocov** [comment]
@everget could you please take a look?

**Comment by ukrit-himakoon** [comment]
:) any chance for this?

**Comment by everget** [comment]
@anboia @ukrit-himakoon try to use another server

**Comment by timocov** [comment]
@anboia @ukrit-himakoon any updates?

**Comment by BeomyeonAndrewKim** [comment]
I have a same issue.
For me, after adding https and domain, above bug happened.

**Comment by timocov** [comment]
Please feel free to reopen it if needed.

**Comment by bs-ravikiran** [comment]
@timocov we are facing same issue in production mode

**Comment by timocov** [comment]
@bs-ravikiran did you try to use another web server as @everget said in https://github.com/tradingview/charting-library-examples/issues/15#issuecomment-400257124?

**Comment by bs-ravikiran** [comment]
Yes, we have tried on another server , it's throwing same error

**Comment by timocov** [comment]
@bs-ravikiran could you please provide a step-by-step reproducing the problem (including starting custom web server, copying files from charting library, etc)?

**Comment by bs-ravikiran** [comment]
1. Go to **react-javascript** folder 
2. Install npm packages (npm install)
3. Copy  **charting_library** and **datafeeds** folders to **public** folder from **tradingview/charting_library**
4. Create production build for react (npm run build)
5. Serve build (serve -s build)
6. Go to browser and open url
7. Check console for error.

**Comment by timocov** [comment]
@bs-ravikiran I confirm that bug is in `serve -s build` command. I just have tried run `python -m SimpleHTTPServer 9090` in `build` folder and it works fine!

**Comment by timocov** [comment]
I do not know why, but `serve` just redirect request for `/charting_library/static/en-tv-chart.html` instead of serving this file from build folder.

**Comment by timocov** [comment]
You even can try to do the following:
1. `cd build`
1. `serve` (without `-s build`)

And it works fine.

**Comment by timocov** [comment]
Or even `serve build` works well.

**Comment by bs-ravikiran** [comment]
@timocov thanks. It's works for me.

**Comment by amanshu-kataria** [comment]
@timocov works fine without `-s`. Also if you test the build in localhost the problem exists but works fine on network.

**Comment by phuthanh19951** [comment]
When i run serve (without -s) command, Routing client has a problem. It shows "the requested path route could be not found". Anyone has the same issue ?

**Comment by mogenshoj** [comment]
Some insights for anyone having this issue.

There can be a number of causes for this depending on your build project, but the problems comes from the iframe not loading the correct html file. The `widgetReady` function is defined in the iframe, if the iframe loads a 404 this error will show up.

Would be nice to have something like:
```
if (typeof i.contentWindow.widgetReady === 'undefined') {
  throw new Error('The iframe does not appear to have loaded correctly, please check your paths');
}
```
It would limit the number of support requests and make the error more usable.

To solve:
Inspect the iframe and verify that the path points to a file that exists.
Possibly set the `library_path` config attribute to point the the correct folder containing the library files, if you're not using the standard configuration.

**Comment by imarun577** [comment]
same issues coming in angular 5

**Comment by PsChina** [comment]
@imarun577  检查下 `libraryPath` 是否正确,也许能解决你的问题。
