### ISSUE TITLE
ReactJS - Files

### ISSUE THREAD

**Issue by whatnowangga** [tradingview/charting-library-examples#171]
Hello
can someone share the file like charting_library and datafeeds ?

**Comment by whatnowangga** [comment]
![image](https://user-images.githubusercontent.com/13533060/80529213-51a9d700-89c1-11ea-8e80-df21c80e231f.png)
i got stuck with this infinite loop

**Comment by timocov** [comment]
> can someone share the file like charting_library and datafeeds ?

It isn't file, it should be folder with charting library content.

**Comment by whatnowangga** [comment]
Yeah i know
where i can get the folder ?

**Comment by timocov** [comment]
From https://github.com/tradingview/charting-library-examples/tree/master/react-javascript:

> Copy charting_library folder from tradingview/charting_library to /public and to /src folders. The earliest supported version of the Charting Library is 1.12. If you get 404 then you need to request an access to this repository.
> Copy datafeeds folder from tradingview/charting_library to /public.
