### ISSUE TITLE
I cannot run his demo

### ISSUE THREAD

**Issue by raycoga** [tradingview/charting-library-examples#172]
**Checklist**

- [ ] This issue is **NOT** related to the charting library itself

**Describe the bug**

i got this error ./src/charting_library/charting_library.min.js
  Line 1:  'define' is not defined  no-undef
  Line 1:  'define' is not defined  no-undef 
and i only do the exact instructions that u post on the repo

**To Reproduce**

1. Clone the repo
2. copy the folders
3. Run command

**Expected behavior**
Im trying to execute his react example to look what u do.

**Screenshots**
![image](https://user-images.githubusercontent.com/50786067/80547583-99f7d380-8986-11ea-9bb6-97120c6744c5.png)

**Additional context**

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104
