### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by Itszeshan** [tradingview/charting-library-examples#175]
Like there is SDK for IOS, isn't there any SDK for Android. I've seen android example in which basically library is loaded from asset folder in a webview. My point is how to create that library which we can then load inside webview.

**Comment by Moshnogorskaya** [comment]
Hello, @Itszeshan!

Please, copy all files from https://github.com/tradingview/charting_library/ to `app/src/main/assets/charting_library/`. The earliest supported version of the Charting Library is 1.12. If you get 404 then you need to [request an access to this repository](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/).

**Comment by Itszeshan** [comment]
Thank you @Moshnogorskaya!

Where can i request access to repo from "https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/" ? When i click on "Get library", it takes me back to github.

**Comment by timocov** [comment]
@Itszeshan on which "Get Library" button you clicked? You need to click on "Technical Analysis Charts"'s one:

![image](https://user-images.githubusercontent.com/3112183/81930152-d0715780-95f0-11ea-98f1-63c4f6fd2ea7.png)

**Comment by Itszeshan** [comment]
Got it, Thanks
