### ISSUE TITLE
Tradingview chart does not work while deploying to production

### ISSUE THREAD

**Issue by ukrit-himakoon** [tradingview/charting-library-examples#18]
The error is as follows:

```
Uncaught TypeError: r.contentWindow.widgetReady is not a function
    at HTMLIFrameElement.t (charting_library.min.js:2)
```

anyone ever experience this?

**Comment by timocov** [comment]
Could you please provide steps to reproduce?

**Comment by ukrit-himakoon** [comment]
It seems to be the react issue related to cache mechanism. We could need to investigate this more on react end first.

**Comment by liuxiaocong** [comment]
Same issue , who can help?

**Comment by bs-ravikiran** [comment]
I am also facing same issue on production mode 

Uncaught TypeError: r.contentWindow.widgetReady is not a function
    at HTMLIFrameElement.t (charting_library.min.js:2)

**Comment by noahjohn9259** [comment]
having the same issue. are there anyone who solved this issue?

**Comment by noahjohn9259** [comment]
disabling service worker solves my issue

**Comment by liutaihua** [comment]
@noahjohn9259  help, which option use to "disabling service worker" ?

**Comment by rhrahul** [comment]
@noahjohn9259 , how did you solve issue ?
Please help :)

**Comment by jonlorusso** [comment]
@rhrahul Return from this function: https://github.com/facebook/create-react-app/blob/26f701fd60cece427d0e6c5a0ae98a5c79993640/packages/react-scripts/template/src/serviceWorker.js#L22

**Comment by nicqchen** [comment]
> disabling service worker solves my issue

how to disable it ?

**Comment by noahjohn9259** [comment]
@nicqchen I am using React on my application. Kindly check if your application is using service worker.

**Comment by lacksfish** [comment]
Check this solution, it worked for me: https://github.com/tradingview/charting-library-examples/issues/110#issuecomment-519492498
