### ISSUE TITLE
How to plot tradingView chart with own data for IOS 

### ISSUE THREAD

**Issue by ahsan084** [tradingview/charting-library-examples#186]
I am trying to populate chart data with own data but didn't find any example.Can anyone tell me how to do that in IOS swift Thanks

**Comment by Moshnogorskaya** [comment]
Hello @ahsan084 !
Here is an iOS example https://github.com/tradingview/charting-library-examples/tree/master/ios-swift

**Comment by ahsan084** [comment]
> Hello @ahsan084 !
> Here is an iOS example https://github.com/tradingview/charting-library-examples/tree/master/ios-swift

Thanks @Moshnogorskaya I have done this thing already and default AAPL is showing now trying to plot my own data like crypto pairs(BTC/USTD) but didn't find any solution to achieve this thing.

**Comment by timocov** [comment]
@ahsan084 you have to implement your own datafeed and pass it to the library's constructor. Or, if you don't like to implement client-side datafeed, you can use UDF impl instead and just implement server-side adapter for it.
