### ISSUE TITLE
Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function

### ISSUE THREAD

**Issue by raghibislam** [tradingview/charting-library-examples#189]
I used this library in react js application with finnhub.io api and getting this error .

×
Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function
(anonymous function)
src/charting_library/charting_library.min.js:314
  311 |   n.addEventListener("load", e, !1);
  312 | })),
  313 | this._innerWindowLoaded.then(function () {
> 314 |   t._innerWindow().widgetReady(function () {
      | ^  315 |     t._ready = !0;
  316 |     for (var e = 0, o = t._readyHandlers; e < o.length; e++) {
  317 |       var n = o[e];
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by timocov** [comment]
Did you look in similar issues https://github.com/tradingview/charting-library-examples/issues?q=is%3Aissue+sort%3Aupdated-desc+widgetReady+is%3Aclosed ?

**Comment by raghibislam** [comment]
Similar but  i have issue on line number 314 . And from the above link I can't solve the issue at all.

**Comment by timocov** [comment]
Can you check what's loading inside iframe? Probably you get 404 or different page there.

**Comment by raghibislam** [comment]
**Please check this image , i hope this will help you**

https://user-images.githubusercontent.com/46419375/96755464-7a4fde00-13f2-11eb-9325-c6d2a29c4ad1.png

Best regards.

**Comment by timocov** [comment]
@raghibislam it doesn't answer on my question. I got your point and seen this error many times, that's why I asked about checking what exactly is loaded inside iframe.

**Comment by green-john** [comment]
Hi @timocov, I hope you are well! I'm also having this same issue.

I am using react and plain js. When I run the example, things work properly and I see the iframe has `src="/charting_library/....."`, however, when running in my react app, the src is missing `/charting_library/`. If I add it manually (as in changing the HTML from inspector) the graph loads. Here's my config 

```es6
const config = {
    libraryPath: '/charting_library/',
    // ...
}
```

Thank you in advance for the help

**Comment by Viktor19931** [comment]
@timocov got same issue on prod build
<img width="447" alt="Screenshot 2021-12-24 at 13 01 29" src="https://user-images.githubusercontent.com/29923015/147347341-96178f41-603d-4560-bed6-3ba0ac29a32d.png">
Followe by https://github.com/tradingview/charting-library-tutorial/blob/master/documentation/integration.md
