### ISSUE TITLE
Error in Trading view chart angular 5 example. 

### ISSUE THREAD

**Issue by stockfinex** [tradingview/charting-library-examples#19]
1 => there is no charting library exist when i download project from github using link 
https://github.com/tradingview/charting-library-examples/

so i have to manually add the charting library js into folder.

**Then i set allow js option into tsconfig.json**

2 => ERROR in app/tv-chart-container/tv-chart-container.component.ts(7,8): 
error TS6143: Module '../../assets/charting_library/charting_library.min' was resolved to 'G:/01 - Important/charting-library-examples-master/charting-library-examples-master/angular5/src/assets/charting_library/charting_library.min.js', 
**but '--allowJs' is not set.**

**Then i set allow js option into tsconfig.json**

**"allowJs": true,**

3=> **Then going to build using ng build option**

**ERROR in app/tv-chart-container/tv-chart-container.component.ts(7,8): error TS2306: File 'G:/01 - Important/charting-library-examples-master/charting-library-examples-master/angular5/src/assets/charting_library/charting_library.min.js' is not a module.**

**Comment by ezhukovskiy** [comment]
Maybe the following issue will help you:
https://github.com/tradingview/charting_library/issues/1516

**Comment by ezhukovskiy** [comment]
If it doesn't help then please create an issue in that repository.
