### ISSUE TITLE
Charts not working in React production build (yarn build/serve)

### ISSUE THREAD

**Issue by umarsa** [tradingview/charting-library-examples#195]
**Checklist**

- [X] This issue is **NOT** related to the charting library itself

I have downloaded the examples from this repo and the charts seem to work just fine when running locally using yarn start. Once you create a production build (yarn build), the resulting web app does not have working charts.

![image](https://user-images.githubusercontent.com/10274401/98845529-c3b9a900-2445-11eb-8728-79902dc7d080.png)

Left is "yarn start". Right is "yarn build", "serve-s build"

**To Reproduce**

1. Clone the repo
2. Copy the trading view library folder and other files as per instructions.
2. Go to 'react-javascript.' folder
3. Run 'yarn start'
4. Observe working charts
5. Stop local development server. Run 'yarn build' then 'serve -s build'
6. Observe unexpected behaviours - non-working charts.

**Expected behavior**

The charts should work in both scenarios.

**Screenshots**

See above

**Additional context**

No additional context

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/issues/15#issuecomment-411001758
