### ISSUE TITLE
Unable to resolve library_path using Vue

### ISSUE THREAD

**Issue by X-AE-A12** [tradingview/charting-library-examples#196]
- [ x  ] This issue is **NOT** related to the charting library itself

**Describe the bug**

`t._innerWindow(...).widgetReady is not a function`
I know this is a common issue, but so far none of the solutions provided to this problem were able to help me out. I am convinced this is library_path issue, though I can't seem to make a proper reference to the path. I am using the Vue.js example and have integrated it in my existing codebase, I have run the example separately too and it ran just fine so its not an issue with my OS but rather with my codebase. 

**Expected behavior**
I expect the Widget to load on it, but it doesn't work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35095979/98937492-c0c2c500-24e6-11eb-90e2-18d225cceeea.png)
As you can see I've shotgunned the `charting_library` pretty much everywhere and yet none of these are recognized. The reference to the widget (@ .min.js) works though.

**Comment by X-AE-A12** [comment]
FYI: my comments about the librarypath is in reference to: https://github.com/tradingview/charting-library-examples/issues/110#issuecomment-519492498

**Comment by timocov** [comment]
Can you please create repro of that?

**Comment by X-AE-A12** [comment]
> Can you please create repro of that?
Sure, here: https://github.com/X-AE-A12/registrarcap-frontend

Just install dependencies and then run `npm run dev`

**Comment by X-AE-A12** [comment]
Any ideas what could be the case here?

**Comment by X-AE-A12** [comment]
Never mind, found the issue. Turns out /static/ is the proper reference

**Comment by melchiebooy** [comment]
> Never mind, found the issue. Turns out /static/ is the proper reference

hi @coinlordd, I have exactly the same problem as you... using vue, tried shotgunning the library everywhere, does not work. spent way to much time on this issue. 

what works:
`npm run serve`

does not work:
`npm run build`
`serve -s dist`  (works without -s flag, but not in production....)

when you say that /static/ is the proper reference, are you refering to the "libraryPath" property circled in blue in picture above?
`libraryPath: '/static/charting_library'` ?
where did you put the charting_library folder in the end?

**Comment by caokhang91** [comment]
....
library_path: 
          process.env.NODE_ENV === "production"
            ? "/assets/charting_library/"
            : "/src/assets/js/charting_library/",
point dev to path "/src/assets/js/charting_library/". I resolved my issue
