### ISSUE TITLE
Module not found: Can't resolve '../../charting_library/charting_library.min'

### ISSUE THREAD

**Issue by OnePieceLiu** [tradingview/charting-library-examples#198]
./src/components/TVChartContainer/index.tsx
Module not found: Can't resolve '../../charting_library/charting_library.min' in 'C:\Users\lz\Desktop\charting-library-examples-master\react-typescript\src\components\TVChartContainer'

**Comment by timocov** [comment]
What version of the library you use?

**Comment by sschiessl-bcp** [comment]
Hello there,

I am running in the same problem using the react-javascript example. I use the latest charting_library (commit hash 02b61a1). It does not contain a min version, and I tried without min as well.

**Comment by sschiessl-bcp** [comment]
I added https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104 to the library js, now I see this error 
![image](https://user-images.githubusercontent.com/33128181/101749477-14b4cf80-3ace-11eb-8652-73bcee703559.png)

**Comment by ivanjulian** [comment]
just try this import:
import { widget } from './charting_library/charting_library';

and also add /* eslint-disable */ at the top of this file to the file from './charting_library/charting_library'; 

For me it works!

**Comment by sschiessl-bcp** [comment]
> just try this import:
> import { widget } from './charting_library/charting_library';
> 
> and also add /* eslint-disable */ at the top of this file to the file from './charting_library/charting_library';
> 
> For me it works!

Which commit hash did you use for the charting_library, and are you running an otherwise unchanged copy of the react-javascript example? I did what you suggested, but it does not work for me and I am running into the error `widgetReady` (see above) ...

**Comment by azivkovi** [comment]
`import { widget } from '../../charting_library/charting_library.esm';` solved this issue for me.

**Comment by aminkhorrami** [comment]
same problem here !

**Comment by option-i** [comment]
I had same problem. the react-javascript is out of date. I did this and it worked. 
![image](https://user-images.githubusercontent.com/69353414/106510615-2c408100-649d-11eb-9c11-d866daaf9be6.png)

**Comment by timocov** [comment]
We're on the way to update all examples to use the latest version of charting_library, see #207.

**Comment by timocov** [comment]
Fixed in #207
