### ISSUE TITLE
Failed to compile. when npm start on localhost

### ISSUE THREAD

**Issue by saimol** [tradingview/charting-library-examples#2]
`sudo npm start`
when i run this command on my ubuntu 14.04 i get below error

> charting-library-react-example@0.1.0 start /var/www/html/workspace/react-example
> react-scripts-ts start

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Watching: /var/www/html/workspace/react-example/src

Starting the development server...

ts-loader: Using typescript@2.7.2 and /var/www/html/workspace/react-example/tsconfig.json
No valid rules have been specified

Failed to compile.

/var/www/html/workspace/react-example/public/datafeeds/udf/src/requester.ts
(32,4): Type 'object' is not assignable to type 'Headers | string[][] | { [key: string]: string; } | undefined'.
  Type 'object' is not assignable to type '{ [key: string]: string; }'.
    Index signature is missing in type '{}'.

**Comment by timocov** [comment]
Try to use the example with `unstable` version of charting library - it should be work fine.

**Comment by saimol** [comment]
Thank you so much!! It worked with unstable version instead of Version 1.12 of charting library. Copy 'datafeeds' and 'charting_library' folders from unstable branch into public folder of 'react-example'

**Comment by timocov** [comment]
It will be fixed with next charting library stable update (I believe tomorrow)

**Comment by timocov** [comment]
For now you can replace `object` [here](https://github.com/tradingview/charting_library/blob/c982afe3f1be566b13915e580a7c775a88b0c538/datafeeds/udf/src/requester.ts#L4) and [here](https://github.com/tradingview/charting_library/blob/c982afe3f1be566b13915e580a7c775a88b0c538/datafeeds/udf/src/requester.ts#L6) with `RequestInit`.
