### ISSUE TITLE
Cannot read property 'initializationFinished' of null

### ISSUE THREAD

**Issue by zhangyu0218** [tradingview/charting-library-examples#20]
This error occurs when I switch the market .Cannot read property 'initializationFinished' of null.
How can I avoid this error

![image](https://user-images.githubusercontent.com/33249149/41703353-952ef86a-7565-11e8-9ecd-a670d7a725c8.png)

**Comment by timocov** [comment]
It seems that this issue is not related to the examples - it is related to the charting library. Please create an issue in [charting library repo](https://github.com/tradingview/charting_library).
