### ISSUE TITLE
everything work fine on vue3 development 

### ISSUE THREAD

**Issue by diadal** [tradingview/charting-library-examples#228]
chart not coming on vue3 `production` but it works fine on `dev` no error even when `debug: true` the loading just keeping running 

<img width="787" alt="Screen Shot 2021-06-03 at 3 59 18 PM" src="https://user-images.githubusercontent.com/19895516/120667027-00ea9480-c485-11eb-9cc2-c6e7d3c8ac3a.png">

**Comment by timocov** [comment]
Can you prepare an example with all changes you made for vue3? It seems that our example is suitable for vue2 only for now.

**Comment by diadal** [comment]
clear cache fix this issue after 6 hours of digging
