### ISSUE TITLE
https://github.com/tradingview/charting_library/wiki has not found.

### ISSUE THREAD

**Issue by Ephinence** [tradingview/charting-library-examples#23]
https://github.com/tradingview/charting_library/wiki was not found but email to me, Trading View CoFounder. 

https://github.com/tradingview/charting_library/wiki link.

but 404 not found.

how to request it?

is this  https://github.com/tradingview/charting_library ?

thnx for  reading.
best regards...

**Comment by timocov** [comment]
It is private repo and you need to get granted access to open it.

Please request a access via https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/.
