### ISSUE TITLE
Fullscreen feature is not working on Chrome 91, Miscrosoft Edge 91

### ISSUE THREAD

**Issue by AlexeyGorbachevskiy** [tradingview/charting-library-examples#230]
Autosize=true in widget constructor.

TradingView fullscreen (Chrome 91):

![image](https://user-images.githubusercontent.com/37103509/120695852-846faa00-c4b4-11eb-977b-fcc957215c65.png)

![image](https://user-images.githubusercontent.com/37103509/120695778-728e0700-c4b4-11eb-82d9-298d39a97e4a.png)

**Comment by AlexeyGorbachevskiy** [comment]
Closed by the reason of this issue refers to charting library itself

**Comment by timocov** [comment]
First of all, it's Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=1213418.
Secondly, we have fixed it already for charting library, see https://github.com/tradingview/charting_library/issues/5745.

**Comment by AlexeyGorbachevskiy** [comment]
@timocov Thanks great.

**Comment by AlexeyGorbachevskiy** [comment]
@timocov  Can you please suggest whether this issue refers to resizing problem or not. (screen attached) Is this fixed in 18 or 19 version? Thanks a lot.
![image](https://user-images.githubusercontent.com/37103509/120794965-8d5a8d00-c541-11eb-98ac-15be7b68d29f.png)

**Comment by timocov** [comment]
@AlexeyGorbachevskiy please see https://github.com/tradingview/charting_library/issues/5745, it was described there
