### ISSUE TITLE
TypeError: Cannot read property 'UDFCompatibleDatafeed' of undefined

### ISSUE THREAD

**Issue by nearshore-macedonia** [tradingview/charting-library-examples#240]
I am getting 

"TypeError: Cannot read property 'UDFCompatibleDatafeed' of undefined"

When i try to run react javascript example. Is this related to some module versions

The error is in: charting-library-examples-master/react-javascript/src/components/TVChartContainer/index.jsx:34

line: datafeed: new window.Datafeeds.UDFCompatibleDatafeed(this.props.datafeedUrl),

I have:
node version: 14.7.3
npm version: 6.14.13

charting_library folder is copied in charting-library-examples-master\react-javascript, public and src folders.

**Comment by timocov** [comment]
> charting_library folder is copied in charting-library-examples-master\react-javascript, public and src folders.

What's about datafeeds folder from 3rd point in https://github.com/tradingview/charting-library-examples/tree/master/react-javascript ?

**Comment by nearshore-macedonia** [comment]
What do you mean?

**Comment by nearshore-macedonia** [comment]
I have copied just part of datafeeds folder so in sense @timocov was right :)
