### ISSUE TITLE
TradingView crashes with Next.js 11

### ISSUE THREAD

**Issue by tjshipe** [tradingview/charting-library-examples#243]
I am using Next.js v 11.1 and the trading view charts also aren't rendering in dev mode. After doing a yarn build and deploying to production they show.

This didn't use to be an issue on Next.js 9.

My guess is it's a problem with webpack 5 though. Previous versions of Next used webpack 4.

![image](https://user-images.githubusercontent.com/1254942/131769008-d8bbc2cb-e180-49d4-92e7-9fe21f77f96c.png)

**Comment by timocov** [comment]
Duplicate of #224

**Comment by phamthainb** [comment]
@tjshipe I have got same issue, do you have solved it?
