### ISSUE TITLE
Add new widget option

### ISSUE THREAD

**Issue by dev1alwin** [tradingview/charting-library-examples#25]
Can't add new widget option. i need to add the new widget option for the changing the default chart type but i can't do it on this package

I added the style option in ChartingLibraryWidgetOptions object in charting_library.min.d.ts

**Comment by timocov** [comment]
And why do you create the issue in this repo? This repo is about examples of integration of the charting library.

Issues about charting library should be here https://github.com/tradingview/charting_library.
