### ISSUE TITLE
By using example  of official repo i got this error on running the project

### ISSUE THREAD

**Issue by nomanabid123** [tradingview/charting-library-examples#258]
src\charting_library\charting_library.esm.js
  Line 77:7:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 88:5:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 123:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 190:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 300:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 302:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 309:11:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 357:7:   Expected an assignment or function call and instead saw an expression  no-unused-expressions        
  Line 465:1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by timocov** [comment]
See https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104
