### ISSUE TITLE
Hide heading info in react javascript example?

### ISSUE THREAD

**Issue by PatSheaFalcon** [tradingview/charting-library-examples#26]
My team is using your react javascript example to display a trading view on our site. The headings currently look like this:
<img width="640" alt="screen shot 2018-07-16 at 11 41 14 am" src="https://user-images.githubusercontent.com/40438547/42776950-7d7b1b9a-88ed-11e8-9e64-6cee57ef47f7.png">

Is there a way to minimize that info by default so that the headings can look like the following image right when the page loads?
<img width="637" alt="screen shot 2018-07-16 at 11 41 26 am" src="https://user-images.githubusercontent.com/40438547/42777006-a78f0004-88ed-11e8-8741-29976c23c9ff.png">

Thank you.

**Comment by ezhukovskiy** [comment]
Please create issues here:
https://github.com/tradingview/charting_library/issues
