### ISSUE TITLE
Update min library version in examples

### ISSUE THREAD

**Issue by icastillejogomez** [tradingview/charting-library-examples#260]
**Checklist**

- [X] This issue is **NOT** related to the charting library itself

**Describe the bug**

When I run the react-typescript error this error occurs.

```
/Users/nacho/Code/charting-library-examples/react-typescript/src/components/TVChartContainer/index.tsx
(56,9): Property 'container' is missing in type '{ symbol: string; datafeed: any; interval: Nominal<string, "ResolutionString">; container_id: string | undefined; library_path: string; locale: LanguageCode; ... 8 more ...; studies_overrides: StudyOverrides | undefined; }' but required in type 'ChartingLibraryWidgetOptions'.
```

**To Reproduce**

1. Clone the repo
2. Go to 'react-typescript' folder
3. Run yarn to install dependencies
3. Copy chartin_library folder inside charting_library repo to src and public folders
4. Copy datafeed folder to public folder
3. Run command yarn start
4. See error in your browser 

**Expected behavior**

See the demo

**Screenshots**
![Captura de pantalla 2021-12-13 a las 0 08 24](https://user-images.githubusercontent.com/16567802/145733317-949bc1fc-1778-4b49-b395-a0fa5b299dd4.png)

**Additional context**
```
❯ node -v
v16.3.0
❯ npm -v
8.1.3
```

**Comment by timocov** [comment]
Please update your charting library version.

**Comment by icastillejogomez** [comment]
I'm using the latest version available @timocov

**Comment by timocov** [comment]
@icastillejogomez what version do you use?

**Comment by icastillejogomez** [comment]
@timocov The current version is: `CL v20.033 (internal id 9df149da @ 2021-11-17T10:20:51.511Z)`

**Comment by timocov** [comment]
Sorry, I misunderstood your issue, my bad. We need to update our samples to make them work correctly with the latest versions.

For now, locally you can try to replace `container_id` with `container` [here](https://github.com/tradingview/charting-library-examples/blob/ce6966b32e649929e75366f66afbda4b18e7bd71/react-typescript/src/components/TVChartContainer/index.tsx#L62).

**Comment by timocov** [comment]
We just updated most of our examples in #269 so I'm going to close this issue for now. Let me know if you need any help or clarification.
