### ISSUE TITLE
I can't execute the project (react-javascript)

### ISSUE THREAD

**Issue by Solviewapp** [tradingview/charting-library-examples#263]
Hello everyone
I need charting_library for react javascript.
Thanks

**Comment by romfrancois** [comment]
Hey @Solviewapp,

You could have a look at https://github.com/tradingview/charting-library-examples and try the react/js examples.

**Comment by romfrancois** [comment]
Hey @Solviewapp,

What exactly is your issue here?
Did you try one of the examples?

**Comment by Solviewapp** [comment]
Thank you for your responding, romfrancois.
I want to use tradingview library for react-javascript.
But I can't find charting_library module.
https://github.com/tradingview/charting_library/
So i need exact module.
Thanks

**Comment by Solviewapp** [comment]
![image](https://user-images.githubusercontent.com/93973520/147195074-92e239d8-99c8-4ea3-9011-b299729db653.png)

**Comment by Solviewapp** [comment]
Hello romfrancois
Could you send me exact charting_library module for react-javascript?

**Comment by romfrancois** [comment]
Try to follow what in [here](https://github.com/tradingview/charting-library-tutorial/blob/master/documentation/getting-started.md).
Basically you need to request access to the repo.

**Comment by Solviewapp** [comment]
Hi, I got charting_library
Thank you for your help.
But Do I have to get chart data?(time, price....)
Do you provide only chart format?
right?

**Comment by timocov** [comment]
> But Do I have to get chart data?(time, price....)

No, we don't have it.
