### ISSUE TITLE
REACT TypeError: this._innerWindow(...).widgetReady is not a function

### ISSUE THREAD

**Issue by Viktor19931** [tradingview/charting-library-examples#265]
got this error on prod build

charting_library.js:1 Uncaught (in promise) TypeError: this._innerWindow(...).widgetReady is not a function

any idea why its happen ? 

appreciate for any help or suggestions!

**Comment by azivkovi** [comment]
What turned out to be the issue?

**Comment by RanjeetAtStackera** [comment]
have same issue with nextjs in prod, can you please help? did you solved the issue?

**Comment by Viktor19931** [comment]
Yes, the problem was that’s all routes should not redirect to index file

**Comment by marcinrabiej** [comment]
> 

I am sorry, I didn't quite catch the resolution - can you please elaborate a bit more on this? How should the routes be set up so that this error doesn't show up?

**Comment by RanjeetAtStackera** [comment]
i am using the nextjs and have same issue on production server only and it works fine on local build as well as on dev, i dont have solution yet.

**Comment by dilnara** [comment]
The same issue. I'm trying to create electron app from existing web app. Web app with trading view iframe works, but inside electron doesn't. Exactly the same error - this._innerWindow(...).widgetReady is not a function.

**Comment by RanjeetAtStackera** [comment]
My issued is solved the problem was we were deployed the site on subdomain when we switched to main domain it worked fine.
check the import path and library url in widget config and also the datafeed script is imported before the page in interactive.

**Comment by Viktor19931** [comment]
This issue occur because import path for trading view is incorrect

**Comment by the-wrong-guy** [comment]
This seems to occur with windows machines mainly, I have solved the issue by changing the library path from `libraryPath: '/charting_library/',` to `libraryPath: 'src/charting_library',`

```js
   public static defaultProps: Omit<ChartContainerProps, 'container'> = {
      symbol: 'AAPL',
      interval: 'D' as ResolutionString,
      datafeedUrl: 'https://demo_feed.tradingview.com',
      libraryPath: 'src/charting_library',
      chartsStorageUrl: 'https://saveload.tradingview.com',
      chartsStorageApiVersion: '1.1',
      clientId: 'tradingview.com',
      userId: 'public_user_id',
      fullscreen: false,
      autosize: true,
      studiesOverrides: {},
   };
```

**Comment by Nicol0rd** [comment]
Where can get the copy for the charting_library folder?

**Comment by 0xAskar** [comment]
I'm having the same issue, in nextjs, however, I give the correct path. Any ideas?
```
window.tvWidget = new TradingView.widget({
        symbol: "Bitfinex:BTC/USD", // default symbol
        interval: "1D", // default interval
        fullscreen: true, // displays the chart in the fullscreen mode
        container: "tv_chart_container",
        datafeed: Datafeed,
        library_path: "public/charting_library_clonned_data",
        });
        
````

**Comment by sonnh58** [comment]
Hi, are you all using Cloudflare ?, Please turn off Rocket Loader™ to fix this issue.

**Comment by xunzhimeng** [comment]
Set ```libraryPath: 'charting_library/'``` works for me.

**Comment by sonnx-oraichain** [comment]
> Hi, are you all using Cloudflare ?, Please turn off Rocket Loader™ to fix this issue.

It worked for me!, thanks
