### ISSUE TITLE
Chart not displaying on hosted website

### ISSUE THREAD

**Issue by rucha0702** [tradingview/charting-library-examples#277]
- **Framework/library:**  : React

Trading view chart is **visible on localhost** but does not display on the hosted website.

Steps followed for integration:
1.Added **charting library** folder in both **public** and **src** folders of the root directory
2.Added **datafeeds** folder in the **public** folder
3.Added **TVChartContainer** in the **components** folder in **src** folder

Tried changing **library_path** in charting but it still didn’t work.

![image](https://user-images.githubusercontent.com/77936051/155298182-da12c46f-012c-461e-acd5-7e216abc9682.png)

**Comment by edew** [comment]
Hi @rucha070

Can you can share a link to the hosted website so we can investigate?

**Comment by rucha0702** [comment]
Hi @edew 
Here's the link: [https://www.sharksigma.com/charts](https://www.sharksigma.com/charts)

**Comment by rucha0702** [comment]
Okay, Thank you for letting me know.
