### ISSUE TITLE
Unexpected use of this page

### ISSUE THREAD

**Issue by OnePieceLiu** [tradingview/charting-library-examples#278]
偶尔加载不到，是神情况
![image](https://user-images.githubusercontent.com/26754729/155984301-1cacb381-5083-4d9b-9856-ed4da88c9999.png)

**Comment by OnePieceLiu** [comment]
Happen by chance

**Comment by romfrancois** [comment]
@OnePieceLiu, which example are you currently on?

**Comment by OnePieceLiu** [comment]
Two language templates will be loaded, resulting in an error, which occurs occasionally
![image](https://user-images.githubusercontent.com/26754729/156533420-21440d73-d776-4d78-a001-98b74952bf20.png)

**Comment by timocov** [comment]
@OnePieceLiu the page you have on your screenshot is not what the charting library has in that file. Please consider disabling any kind of booster or so for charting library.
