### ISSUE TITLE
WebSocket Socket.IO 

### ISSUE THREAD

**Issue by Swaprusher** [tradingview/charting-library-examples#279]
Did you have any example of backend working with websocket or socket.io ?

**Comment by timocov** [comment]
I believe this repo is mostly for examples of integrations charting library to the client side, not examples for datafeeds in any kind. Thus no, we don't have such examples and I don't think that we're going to add them at least to this repo.

Usually customers already have their API and want to connect their data to charting library, but it seems you don't the API either.
