### ISSUE TITLE
react hook this._innerWindow(...).widgetReady is not a function

### ISSUE THREAD

**Issue by bi123co** [tradingview/charting-library-examples#282]
react-typescript project  in  charting-library-examples is running ok ,but I have a react-hook project using tradingview,  it returns this._innerWindow(...).widgetReady is not a function
 
ps: I copied charting_library and datafeeds in src, and charting_library in src

can anyone know how to solve it?
best wishes

**Comment by bi123co** [comment]
I have tried 
library_path: 'src/charting_library/',
libraryPath: 'src/charting_library/',
library_path: 'public/charting_library/',
libraryPath: 'public/charting_library/',

but it's still  "this._innerWindow(...).widgetReady is not a function"

**Comment by bi123co** [comment]
ps :  I got a version like "CL v21.064 (internal id f0bc1e45 @ 2022-03-17T12:19:26.809Z)" from "src/charting_library"

**Comment by romfrancois** [comment]
Closing as [duplicate](https://github.com/tradingview/charting_library/issues/6580).
