### ISSUE TITLE
Attempted import error: 'widget' is not exported from

### ISSUE THREAD

**Issue by duanescarlett** [tradingview/charting-library-examples#284]
I am integrating the NextJS example into my NextJS project but I am getting an import error, I am not able to import widget and version from charting_library. Does anyone have any clues as to why this might be happening?

![importError](https://user-images.githubusercontent.com/1207629/160896305-bf5352f2-b2dd-4dae-9343-8f204147e426.png)

**Comment by ramirezsandin** [comment]
That library is missing from the repos for any reason I don't know.

**Comment by duanescarlett** [comment]
I was able to resolve the issue by upgrading the next module to the latest version in package.json
