### ISSUE TITLE
TradingView chart render issue

### ISSUE THREAD

**Issue by toyazp** [tradingview/charting-library-examples#289]
After logging out and again login in application while trying to open any chart i am facing below error and chart is not getting displayed :
" Uncaught ReferenceError: DEFAULT_SYMBOL is not defined"

But after refreshing the page this issue get solved and chart works properly

Any help will be Appreciated

**Comment by eugene-korobko** [comment]
Hello!

Try providing symbol while creating a chart widget

**Comment by toyazp** [comment]
Thanks for reply it got solved by using below code in widget:
  symbol: sym ? sym : "TCS",
