### ISSUE TITLE
How can bind own data in datafeed?

### ISSUE THREAD

**Issue by kevalkk** [tradingview/charting-library-examples#3]
I has download charting_library and run it. i want to display BTC(bitcoin) chart. 
There is code like
TradingView.onready(function()
			{
				var widget = window.tvWidget = new TradingView.widget({
					// debug: true, // uncomment this line to see Library errors and warnings in the console
					fullscreen: true,
					symbol: 'AAPL',
					interval: 'D',
					container_id: "tv_chart_container",
					//	BEWARE: no trailing slash is expected in feed URL
					datafeed: new Datafeeds.UDFCompatibleDatafeed("https://demo_feed.tradingview.com"),
					library_path: "charting_library/",
					locale: getParameterByName('lang') || "en",
					//	Regression Trend-related functionality is not implemented yet, so it's hidden for a while
					drawings_access: { type: 'black', tools: [ { name: "Regression Trend" } ] },
					disabled_features: ["use_localstorage_for_settings"],
					enabled_features: ["study_templates"],
					charts_storage_url: 'http://saveload.tradingview.com',
                    charts_storage_api_version: "1.1",
					client_id: 'tradingview.com',
					user_id: 'public_user_id'
				});
			});
---------------------------------------------------------
1. datafeed url on which format data would be?
2. i had change my site url at charts_storage_url and symbol:BTCUSD but nothing happen?
3. i had setup my datafeed url which has responce like 
{"status":"success","result":[{"id":"196","Qty":"20000.00000000","Price":"5.00","exactprice":"100000.00000000","dateexecuted":"2018-03-08 11:18:56","timestamp":"1520488136"},{"id":"195","Qty":"1.00000000","Price":"20000.00","exactprice":"20000.00000000","dateexecuted":"2018-03-08 11:19:20","timestamp":"1520488160"},{"id":"194","Qty":"1.00000000","Price":"19000.00","exactprice":"19000.00000000","dateexecuted":"2018-03-08 11:19:15","timestamp":"1520488155"},{"id":"193","Qty":"1.00000000","Price":"17000.00","exactprice":"17000.00000000","dateexecuted":"2018-03-08 11:19:09","timestamp":"1520488149"},{"id":"192","Qty":"1.00000000","Price":"16000.00","exactprice":"16000.00000000","dateexecuted":"2018-03-08 11:19:02","timestamp":"1520488142"},{"id":"191","Qty":"1.00000000","Price":"16000.00","exactprice":"16000.00000000","dateexecuted":"2018-03-08 11:13:50","timestamp":"1520487830"},{"id":"190","Qty":"1.00000000","Price":"16000.00","exactprice":"16000.00000000","dateexecuted":"2018-03-08 11:13:50","timestamp":"1520487830"},{"id":"189","Qty":"1.00000000","Price":"16000.00","exactprice":"16000.00000000","dateexecuted":"2018-03-08 11:10:22","timestamp":"1520487622"},{"id":"188","Qty":"1.00000000","Price":"16000.00","exactprice":"16000.00000000","dateexecuted":"2018-03-08 11:10:22","timestamp":"1520487622"},
can you explain me in which format json data would be?
4. how can i change chart to own trading bitcoin data view chart?

explain me asap. thanks in advance.

**Comment by timocov** [comment]
Please create issue in https://github.com/tradingview/charting_library.
