### ISSUE TITLE
React-native Readme with dead link

### ISSUE THREAD

**Issue by Xplosive06** [tradingview/charting-library-examples#304]
4. Copy all files from [https://github.com/tradingview/charting_library/](https://github.com/tradingview/charting_library/.) The earliest supported version of the Charting Library is 17. If you get 404 then you need to [request an access to this repository](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/).

This link is dead: https://github.com/tradingview/charting_library/

Can we get the good onde?

**Comment by Xplosive06** [comment]
Sorry, Monday, i'm not awake yet...

**Comment by Nicol0rd** [comment]
Did you manage to get a new link?
