### ISSUE TITLE
Re nextjs: widget, version  Missing from from '../../public/static/charting_library';

### ISSUE THREAD

**Issue by Nicholas0350** [tradingview/charting-library-examples#305]
nextjs line 3 index.js  is importing import { widget, version } from '../../public/static/charting_library';  .
./static folder is missing as is charting_library file

**Comment by 0xAskar** [comment]
i have the same error and i got rid of the version. did you end up getting yours to work? i'm having a nextjs errors such as this after doing everything as explained. were you able to get yours to work?
<img width="759" alt="image" src="https://user-images.githubusercontent.com/37524379/203467411-2fc2a7b8-e18a-491d-9d65-32d91148ef62.png">

**Comment by srivastavarnav** [comment]
+1 Is there any update on this issue?

**Comment by romfrancois** [comment]
We updated this specific [example](https://github.com/tradingview/charting-library-examples/tree/master/nextjs-javascript) a few weeks back?
Is it still not working?

At present time only next < v13 is supported but we're planning on providing another example for that version onwards.
