### ISSUE TITLE
 sveltekit - TypeError: this._innerWindow().widgetReady is not a function

### ISSUE THREAD

**Issue by jakubdonovan** [tradingview/charting-library-examples#307]
# Bug Report
> TypeError: this._innerWindow().widgetReady is not a function

It is caused by `library_path: libraryPath: '../../src/lib/charting_library/';`

Upon inspecting the iframe, I can see that the src attribute does indeed point to the correct file with the correct locale, but the iFrame still refuses to load. Is there anything obvious you can see here that I might have messed up?
<img width="1141" alt="Screenshot 2022-09-02 at 16 43 48" src="https://user-images.githubusercontent.com/16073448/188112704-0d09ce47-80d9-4ade-af57-1068d5357ad4.png">
<img width="1142" alt="Screenshot 2022-09-02 at 16 44 07" src="https://user-images.githubusercontent.com/16073448/188112617-be7c44f1-9905-4ff8-b735-3243325620ca.png">

**Charting Library Version**
"CL v22.032 (internal id e2a841ff @ 2022-07-06T11:53:07.702Z)"

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 
 - Browser: Firefox Developer
 - Browser version: 105.0b3 (64-bit)
 
**To Reproduce**
1. Clone my repo https://github.com/jakubdonovan/technical_charts_sveltekit
2. Run npm run dev in terminal

**Comment by SlicedSilver** [comment]
The `TypeError: this._innerWindow().widgetReady is not a function` error occurs when the created iframe doesn't have a valid `src` url, and thus the browser can't download and display the correct html file within the iframe.

**The solution is to specify the `library_path` relative to the current pages url (as seen by the browser).**

For example, if the library files are hosted at `www.example.com/charting_library` and the current page is `www.example.com/charts/my-chart.html` then the `library_path` should be set to either `../charting_library/` or `/charting_library/`.

In your case, you would probably want to serve the library files from a folder called `charting_library` placed inside the `static` folder and then use `/charting_library/` as the value for the `library_path`.
