### ISSUE TITLE
Linux manjaro 5.19.1-3 KDE Bug TV

### ISSUE THREAD

**Issue by Js8Uq0Iqu** [tradingview/charting-library-examples#309]
Hi. 
Installed according to your instructions from the site TradingView, the program runs for 3-4 days then stops to run. The system was not updated, no packages were installed. Run the program in the terminal and there is an error as in the screenshot. After uninstalling and reinstalling the snap package, everything works fine.

screenshot - https://imgur.com/a/6FzcdJP

**Comment by edew** [comment]
HI @Js8Uq0Iqu 

Is your error with the desktop app?

**Comment by Js8Uq0Iqu** [comment]
Yes. Install TV Instructions -  https://snapcraft.io/install/tradingview/manjaro
watch screenshot - https://imgur.com/a/6FzcdJP

**Comment by edew** [comment]
OK. We don't provide support for the desktop app on GitHub, only our self hosted software libraries.

You can open a support ticket and the desktop support team should be able to help you https://www.tradingview.com/support/tickets/
