### ISSUE TITLE
vue is not work

### ISSUE THREAD

**Issue by shiyunsheng** [tradingview/charting-library-examples#31]
As shown
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/10612112/43043987-1cd9135e-8dd0-11e8-939a-1d80594f5ce1.png">

**Comment by timocov** [comment]
Could you please provide steps to reproduce it?

**Comment by ALX-TH** [comment]
Just follow the installation steps in the readme.md and got the same result as on the screen above.

**Comment by ALX-TH** [comment]
@timocov  please check for operability

**Comment by timocov** [comment]
Guys, please make sure that you copy right folder from charting_library repo to the `public` folder in example.

The doc says:

>  Copy `charting_library` folder from https://github.com/tradingview/charting_library/ to `/public` folder.

This means that you need to copy whole folder https://github.com/tradingview/charting_library/tree/master/charting_library to `public`, *not root of the repository*.

As result you need to get the following fs structure of the `public` folder:

```
$ tree -d -L 3 public/
public/
├── charting_library
│   └── static
│       ├── bundles
│       ├── fonts
│       ├── images
│       └── lib
└── datafeeds
    └── udf
        ├── dist
        ├── lib
        └── src
```
