### ISSUE TITLE
Renders blank screen in iOS 14 with React Native

### ISSUE THREAD

**Issue by salman-ar-sar** [tradingview/charting-library-examples#327]
**Checklist**

- [x] This issue is **NOT** related to the charting library itself

**Describe the bug**

I am working on integrating TradingView into my react native app. I have put the library into it. It is working fine in android and iOS 15 and above. But on iOS 14 I am getting a blank screen with no error in metro.
When I tried to debug using Safari inspector I am getting this error:
`Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.)`
Any idea what could be the issue and how to solve it?

**To Reproduce**

1. Clone the repo
2. Go to 'react-native' folder and do the basic setup. Copy library.
3. Run command - yarn ios
4. Blank screen appears

**Expected behavior**

The chart should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/16640612/221554045-24b767b5-5e88-448c-ba29-748ffd66e747.png)
![image](https://user-images.githubusercontent.com/16640612/221554126-022796e5-3ed9-488f-90f4-52fc29595412.png)
![image](https://user-images.githubusercontent.com/16640612/221554211-afbc5802-d15e-44d3-ab3f-f8997b2631e7.png)

**Additional context**

Works fine in iOS 15 and 16 and in Android. For some reason, iOS 14 is not getting all the source files

**Comment by SlicedSilver** [comment]
This is a Safari bug on the older versions of iOS. We recently implemented a fix for this. Could you please try this again with either `v23.047` or `v24.000`?

**Comment by salman-ar-sar** [comment]
> This is a Safari bug on the older versions of iOS. We recently implemented a fix for this. Could you please try this again with either `v23.047` or `v24.000`?

`V23/24` of the Charting library right?

**Comment by salman-ar-sar** [comment]
That worked. That was the issue. Thank you @SlicedSilver!

Closing this issue.
