### ISSUE TITLE
Chart look really odd and weird on small screens. 

### ISSUE THREAD

**Issue by rahulpunase** [tradingview/charting-library-examples#342]
**Describe the bug**

Chart look really odd and weird on small screens. Added the SS below. Is their any property or override I have to add to make it work?

**Expected behavior**

The price-axis scale should automatically adjust itself. And so should chart zoom

**Screenshots**

![Screenshot from 2023-05-25 09-52-33](https://github.com/tradingview/charting-library-examples/assets/16353682/eb38f3ce-d7a3-46c2-95f8-e9ba917d811f)

**Comment by romfrancois** [comment]
Hi @rahulpunase !

Are you by any chance testing on a real device or is it coming from the browser emulation?

**Comment by vinayak-ventura** [comment]
@rahulpunase experiencing same problem, you got any work around ?

**Comment by romfrancois** [comment]
>Are you by any chance testing on a real device or is it coming from the browser emulation?

**Comment by AminJafarlou** [comment]
Any solutions for this?? I have the same problem

**Comment by romfrancois** [comment]
https://github.com/tradingview/charting-library-examples/issues/342#issuecomment-1588819976

**Comment by rahulpunase** [comment]
@romfrancois @AminJafarlou Yes. On real devices it it okay. The image attached in the issue is the screenshot of the chrome responsive emulation.

**Comment by rahulpunase** [comment]
> [#342 (comment)](https://github.com/tradingview/charting-library-examples/issues/342#issuecomment-1588819976)

@romfrancois @AminJafarlou Yes. On real devices it it okay. The image attached in the issue is the screenshot of the chrome responsive emulation.

**Comment by romfrancois** [comment]
At this point this is a Chrome issue and there's nothing TradingView can do about it.
I'll close this ticket.
