### ISSUE TITLE
Are the chart override options documented somewhere?

### ISSUE THREAD

**Issue by chovy** [tradingview/charting-library-examples#35]
Are the chart override options documented somewhere?

**Comment by timocov** [comment]
Yes, in other repository.

https://github.com/tradingview/charting_library/wiki/Overrides

**Comment by chovy** [comment]
I get a 404 there.

**Comment by timocov** [comment]
If you get 404 then you need to request an access to this repository.

https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
