### ISSUE TITLE
Can I use Tradingview widgets in Angular?

### ISSUE THREAD

**Issue by Shentia** [tradingview/charting-library-examples#350]
- **Framework/library:** 
- **Link to page with the framework/library:** 
Hi there! I appreciate the TradingView widgets you provided. I just want to confirm if it's possible to use TradingView in Angular while also customizing the widgets.

appreciated

**Comment by Shentia** [comment]
how much is possible to customize the widgets such as add icons or color or change style like border radius and .... 
is it  doable in tradingview widgets ?

**Comment by romfrancois** [comment]
I would advise looking at the [documentation](https://www.tradingview.com/charting-library-docs/latest/customization/) to better understand what's available and what's not.

**Comment by tradingproject19** [comment]
@romfrancois  i am getting the following error with angular. is there any solution to this?

![image](https://github.com/tradingview/charting-library-examples/assets/50413570/d9c9438a-89d4-4826-b561-5f5593fcf5bd)

**Comment by romfrancois** [comment]
Looks like a tsconfig issue.
Have a read [here](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature).
