### ISSUE TITLE
Tradingview Charting library doesn't work on web view of metamask mobile app.

### ISSUE THREAD

**Issue by MapleDev423** [tradingview/charting-library-examples#352]
**Describe the bug.**

Tradingview which is using charting library doesn't work on web view of metamask app on mobile.
I think this is because Tradingview widget uses **blob** url for the Iframe.

**Expected behavior**

This url should be work on webview of metamask app on mobile.
https://charting-library.tradingview-widget.com/

![image](https://github.com/tradingview/charting-library-examples/assets/67868337/c7b221dd-153c-4829-943d-0bd7f27c40f4)

**Comment by SlicedSilver** [comment]
Please see here:
https://github.com/tradingview/charting_library/issues/7717
