### ISSUE TITLE
Sample react code -> Unhandled Runtime Error Error: There is no such element - #

### ISSUE THREAD

**Issue by dsldsl** [tradingview/charting-library-examples#361]
I have spent about 20+ hours trying to get a sample working in React + Typescrypt.  I have tried the base sample React code on the website and many different variations in this React + Typescripe example libary as well as the Nextjs examples.  (I am using nextjs but not using any of the next specific functionality in my app other than running the code through `next dev` command.)

The error that I can't get past is:

![image](https://github.com/tradingview/charting-library-examples/assets/50015/0ce37796-61a6-4feb-b127-78256a5cb5c7)

The error gets thrown here:

```
      function createWidget() {
        if (document.getElementById('technical-analysis-chart-demo') && 'TradingView' in window) {
          new window.TradingView.widget({
            container_id: "technical-analysis-chart-demo",
            width: "100%",
            height: "100%",
            autosize: true,

```

Considering the widget constructor is thrown within an if statement checking that the container exists, I'm not sure what to make of the fact that the error is saying there is no such element.

Any help is greatly appreciated.  I have tried so many different variations and am very familiar with React and associated workflows.  Thank you!

**Comment by dsldsl** [comment]
FWIW, I can't even run the first step of the example typescript-react project when I check it out.  npm install gives all kinds of errors on version and dependencies.

**Comment by romfrancois** [comment]
Hmm you don't seem to have checked out our example 🤔 
Ours is [here](https://github.com/tradingview/charting-library-examples/tree/master/react-typescript).

**Comment by dsldsl** [comment]
Thank you for the reply.  The example was not working for me.  I have gotten it working now.  Will propose some updates in a PR once I get the rest working.
