### ISSUE TITLE
'define' is not defined - ReactJS

### ISSUE THREAD

**Issue by DamianRavi** [tradingview/charting-library-examples#42]
I seem to get an issue using Truffle React-Box with charting_library/charting_library.min where I am given the error:

  1:107   error    'define' is not defined                                                                                     no-undef
  1:118   error    'define' is not defined                                                                                     no-undef

The line in question:
"undefined"!=typeof module?e(exports):"function"==typeof define&&define.amd?define(["exports"],e):e(t.TradingView=t.TradingView||{})

**Comment by DamianRavi** [comment]
Literally the next thing I tried fixed it: https://eslint.org/docs/rules/no-undef

At the top of charting_library.min adding:
/*global define:true*/
/*eslint no-undef: "error"*/

**Comment by kanpou0108** [comment]
I experienced the same issue.
Adding the line below to the top of `react-javascript/src/charting_library/charting_library.min.js` works fine for me.

```
/* eslint-disable */
```
