### ISSUE TITLE
'define' is not defined  no-undef

### ISSUE THREAD

**Issue by coinloop** [tradingview/charting-library-examples#43]
I clone react-javascript demo,
then yarn install packages
and put charting_library file to destination dir
and yarn start
the browser and terminal output errors

```
Failed to compile
...... in charting_library.min.js
  Line 1:  'define' is not defined  no-undef
  Line 1:  'define' is not defined  no-undef

Search for the keywords to learn more about each error.
```

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104

**Comment by wangshuang0** [comment]
I have the same problem. How to solve？

**Comment by fintegri** [comment]
Hi,

I too have same problem please help to implement that

**Comment by SavosRU** [comment]
I have same error too... 
But no found any answers to this issue - only duplicate questions from developers like we all

**Comment by timocov** [comment]
> But no found any answers to this issue 

https://github.com/tradingview/charting-library-examples/issues/43#issuecomment-413478478
