### ISSUE TITLE
iOS example

### ISSUE THREAD

**Issue by roktoshl** [tradingview/charting-library-examples#44]
- **Android**
- **iOS**

**Comment by roktoshl** [comment]
## Android

1. Put the whole chart library (https://github.com/tradingview/charting_library) into src/main/assets
2. Create a webview in your main layout
3. Load the chart into the layout

```
webView.settings.javaScriptEnabled = true
webView.settings.allowContentAccess = true
webView.settings.allowFileAccess = true
webView.webViewClient = WebViewClient()
webView.loadUrl("file:///android_asset/mobile_white.html")
```

**Comment by jbetancourt8** [comment]
How would you implement TradingView charts using React Native?

**Comment by roktoshl** [comment]
Perhaps you can try the same way as with a native Android app, to load it as a local file. Check out this tutorial on how  to load a local html content into a WebView:
* https://medium.com/@snehabagri.90/reactnative-webview-with-local-content-c98a09340801

**Comment by timocov** [comment]
Android example is in master (https://github.com/tradingview/charting-library-examples/tree/master/android). Thanks @roktoshl.

**Comment by zhangjianlin77** [comment]
Do you have the native lib of android or ios,  not js files.   How can i implemente the tradingview like binance  app??

**Comment by timocov** [comment]
> Do you have the native lib of android or ios, not js files

No, we haven't such lib.

**Comment by ianeinser** [comment]
@roktoshl @timocov how can i integrate reactjs to this android example? reactjs has two directories namely public and src. I want to integrate the files in src in android webview. Thanks

**Comment by ianeinser** [comment]
> I guess that you need to bundle your app and place it in android app.

Can you be more specific. There is a reactjs example in this repo. can you show how?

**Comment by roktoshl** [comment]
@ianeinser Can you check this tutorial https://medium.com/@snehabagri.90/reactnative-webview-with-local-content-c98a09340801, specifically placing the assets in the correct subfolder:
* Android: <react-native-project>/android/app/src/main/assets/
* iOS: <react-native-project>/ios/<new group as folder>/ (Note: “New group as folder” will ensure all its contents are bundled into the IPA file.)

**Comment by ianeinser** [comment]
> @ianeinser Can you check this tutorial https://medium.com/@snehabagri.90/reactnative-webview-with-local-content-c98a09340801, specifically placing the assets in the correct subfolder:
> 
> * Android: /android/app/src/main/assets/
> * iOS: /ios// (Note: “New group as folder” will ensure all its contents are bundled into the IPA file.)

Okay.. I am trying it out.. i have three questions.. under reactjs scenario 
1. which folder will be placed in /android/app/src/main/assets? the public or the src directory? the src directory does not contain any index.html
2. in the tutorial, two java files are used, but in the android example in this repo, two kotlin files are used.. which ones should i use? the java or the kotlin ones?
3. regardless the java or the kotlin ones are used, which file in public or src should i point to? in the android example, the index.html in /charting_library is pointed. what about under reactjs?

i am interested to integrate reactjs because it is easier for me to develop js api in reactjs. Thanks

**Comment by tahlilaty** [comment]
Hi i have downloaded the sample the cart lib works just fine for android but for ios it does not load anything. As i think there are some path issue. Is the charting_library is different for ios or same library is used?

**Comment by timocov** [comment]
> there are some path issue. Is the charting_library is different for ios or same library is used?

@tahlilaty what do you mean? I believe there should be the same library for every example in this repo.
