### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by roktoshl** [tradingview/charting-library-examples#45]
- **Vanilla JS with static HTML**

**Comment by timocov** [comment]
What's about https://github.com/tradingview/charting_library/blob/master/index.html#L24-L45?

**Comment by coditori** [comment]
@timocov your sample just used "demo-feed-data.tradingview" datafedd we need a local sample

**Comment by lonewold999** [comment]
> @coditori to be honest, I didn't quite get what exactly @roktoshl suggestion is about. Vanilla JS example? The library's API is pure Vanilla JS. So I'm about to close the issue so far. If you'll have more information, please feel free to create an issue with all that information.
> 
> > we need a local sample
> 
> What does it mean?

I think that this means they need the local data example, e.g. not from trading view but their own data.
Like this 
{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 },{ time: '2018-10-19', open: 54.62, high: 55.50, low: 54.52, close: 54.90 }
