### ISSUE TITLE
Hello! Need help with chart settings

### ISSUE THREAD

**Issue by Ganuka** [tradingview/charting-library-examples#46]
1. How to get the js values of high, low, close, volume with the help of your api to the bar graphics on which the cursor is hovered http://prntscr.com/kl5422?
2. How to display the month and date on the timeline of the chart https://prnt.sc/k4djkk?

**Comment by ezhukovskiy** [comment]
This repo is about examples of integration of the charting library.

Issues about charting library should be here https://github.com/tradingview/charting_library.

**Comment by Ganuka** [comment]
Page not found 404

**Comment by ezhukovskiy** [comment]
Where did you get the Charting Library package?
