### ISSUE TITLE
Babel needed

### ISSUE THREAD

**Issue by CILP** [tradingview/charting-library-examples#49]
**Checklist**
- [x] This issue is **NOT** related to the charting library itself

I was stucked trying to implement the example with same files with a new generated vue-cli project, and I noticed and it's very important to mention that we need `babel-core` and `babel-loader`, I think this can will be useful for other people.

**Comment by timocov** [comment]
What do you mean? Can you please add more info what you did and what didn't work?

**Comment by CILP** [comment]
I generated a new vue-cli project `3.0.1` and when I tried to replicate the tradingview demo for vuejs I got some webpack errors, and I found that in the tradingview demo for vuejs the package.json contains those babel dependencies, the new cli project doesn't had `babel-core` nor `babel-loader`, So, I installed `babel-core` and `babel-loader` and the project run successfully .
