### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by bfischer1121** [tradingview/charting-library-examples#5]
Would it be possible to get a description of the data format(s) compatible with the chart?

For example, is OHLCV the ideal data format? If so, would we need to be able to supply data for 1 minute periods?

We're not yet ready to tackle integration & legal agreement, but want to ensure the backend is designed to handle the requirements. Thank you!

**Comment by ezhukovskiy** [comment]
data is supplied in OHLCV
if you need 1,5,15... minute bars you'll need to supply 1 minute bars
if you need only daily, weekly and monthly, you won't need that

**Comment by paragsatpute** [comment]
If we get tick data from WebSockets then would it still require 1 minute bars data?
