### ISSUE TITLE
failed compile

### ISSUE THREAD

**Issue by NeWay2002** [tradingview/charting-library-examples#54]
**Checklist**

- [ ] This issue is **NOT** related to the charting library itself

**Describe the bug**

Sorry for english. I got the library from the official site. And I wanted to run an assembly example from this repository. But this causes an error.
The first thing the debugger shows is on "line1: define is not define". Then I tried to fix it but without success. I just ran the assembly without this string. but eventually got even more errors. What's wrong?

**To Reproduce**

1. Clone the repo
2. Put library into /public and /src, and datafeed into /public
3. npm install
4. npm start

**Expected behavior**

![image](https://user-images.githubusercontent.com/25829053/44655342-6f10eb80-a9fd-11e8-9e56-025afe1330c6.png)
![image](https://user-images.githubusercontent.com/25829053/44655450-ca42de00-a9fd-11e8-8dee-18c9e56903a8.png)
![image](https://user-images.githubusercontent.com/25829053/44655244-1f322480-a9fd-11e8-9c6b-6de1c846a3ed.png)
![image](https://user-images.githubusercontent.com/25829053/44655269-340eb800-a9fd-11e8-8e93-2ee3293e3c4e.png)

any ideas?

**Comment by timocov** [comment]
> The first thing the debugger shows is on "line1: define is not define". Then I tried to fix it but without success.

Did you try to find the similar issues?

> Put library into /public and /src, and datafeed into /public

What example do you use? React?

**Comment by NeWay2002** [comment]
Thanks for the quick answer
of course, I spent a few days reading and trying out different options. I'm new to the graphics library. 
as an example I added a babel, edit code. Yes, I use the example with react-javascript

![image](https://user-images.githubusercontent.com/25829053/44656286-fc097400-aa00-11e8-92e1-4620618c2312.png)

npm 6.3.0

**Comment by NeWay2002** [comment]
maybe you downloaded the example with react and you all works well?

**Comment by timocov** [comment]
Yes, it works well.

Can you please tell me where did you get the charting library?

**Comment by NeWay2002** [comment]
![image](https://user-images.githubusercontent.com/25829053/44662690-2cf4a380-aa17-11e8-9e48-696ceff8617a.png)

Здесь, на сайте делал запрос. Так значит проблема в файле?

**Comment by NeWay2002** [comment]
А вы можете дать свой вариант библиотеки?

**Comment by timocov** [comment]
Please use English. With what username you request access?

**Comment by NeWay2002** [comment]
webdevepru
this is github username

**Comment by NeWay2002** [comment]
Sorry for taking your time and thanks.
it seems I have found a solution

**Comment by magzak** [comment]
I have the same problem, what solution did you find?

I just cloned the repos and followed the instructions for react-javascript and get the following error after npm start:

Failed to compile.

./src/charting_library/charting_library.min.js
  Line 1:  'define' is not defined  no-undef
  Line 1:  'define' is not defined  no-undef

**Comment by magzak** [comment]
@NeWay2002 Can you please let me know how you solved this?

**Comment by SavosRU** [comment]
@NeWay2002 Can you please let ME TOO know how you solved this?

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104
