### ISSUE TITLE
javascript example can not run

### ISSUE THREAD

**Issue by zxmzhyzkp** [tradingview/charting-library-examples#55]
Failed to compile
./src/charting_library/charting_library.min.js
  Line 1:  'define' is not defined  no-undef
  Line 1:  'define' is not defined  no-undef

Search for the keywords to learn more about each error.
This error occurred during the build time and cannot be dismissed.

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/blob/master/CONTRIBUTING.md#creating-new-issue
