### ISSUE TITLE
Library does not work in React javascript production build.

### ISSUE THREAD

**Issue by MettaProgrammer** [tradingview/charting-library-examples#56]
To reproduce simply npm run build and then serve the build.

iFrame just creates a copy of the page, error in the console is: 
`Uncaught TypeError: r.contentWindow.widgetReady is not a function at HTMLIFrameElement.t`

Also have the same problem outside of this example with chart implemented in my own app, runs fine in dev mode, fails in production.

**Comment by timocov** [comment]
Do you have the latest version of react example?

**Comment by timocov** [comment]
Did you see #18 and #15?

**Comment by MettaProgrammer** [comment]
I did, apologies.

**Comment by tongyantee** [comment]
I am also facing similar issue with the following error "TypeError: i.contentWindow.widgetReady is not a function" and i am not using React or IHTML. I am using Laravel with a common blade layout inherited by the blade.php that  is supposed to display TradingView.

**Comment by tazotodua** [comment]
Check this solution: https://github.com/tradingview/charting-library-examples/issues/110#issuecomment-519492498

**Comment by valervarga** [comment]
This one worked for me: [#5 (comment)](https://github.com/jonchurch/tradingview-js-api-tutorial/issues/5#issuecomment-629694127)
