### ISSUE TITLE
Vuejs: export 'widget' was not found in './charting_library.min'

### ISSUE THREAD

**Issue by hungnm10** [tradingview/charting-library-examples#57]
I create vuejs app using
<code> vue init webpack my-project </code>
Then import charting-library but when I compiled, it got an error in TVChartContainer.vue file
"export 'widget' was not found in './charting_library.min'
Please check this issue. Thank you!

**Comment by timocov** [comment]
Did you see our example https://github.com/tradingview/charting-library-examples/tree/master/vuejs?

**Comment by hungnm10** [comment]
Yes, I checked this example but I got the issue when I using vue-cli to create application as I mentioned above.

**Comment by timocov** [comment]
> Now, tradingview charting library has not supported for Vuejs javascritp, it only supported veujs using type-script???

No, it support any language you want to use.

> Yes, I checked this example but I got the issue when I using vue-cli to create application as I mentioned above.

Please check the structure of the folders. I believe that the reason of your error is there.

**Comment by timocov** [comment]
Did you have access to https://github.com/tradingview/charting_library repo?

**Comment by hungnm10** [comment]
Yes, I did it follow your instruction

**Comment by CILP** [comment]
Hi @hungnm10 I was experimenting the same problem, I was using Vue CLI v3 and this works for me, #49

**Comment by hungnm10** [comment]
Thanks @CILP . I have solved it by other way like below
<code>const tvWidget = new window.TradingView.widget(widgetOptions);</code>

**Comment by sidsverma** [comment]
I am still facing this issue.
@CILP can't fix it even after installing babel-core and babel-loader.
@hungnm10 changing that line to the one mentioned by you also does not fix that issue.

**Comment by aaron13347815** [comment]
I am still facing this issue.
@CILP can't fix it even after installing babel-core and babel-loader.
@hungnm10 changing that line to the one mentioned by you also does not fix that issue.

**Comment by aaron13347815** [comment]
warning  in ./src/components/TVChartContainer.vue?vue&type=script&lang=js&
"export 'widget' was not found in '../charting_library.min'

**Comment by envyTang** [comment]
*index.html*
```
<script src="<%= BASE_URL %>charting_library/charting_library.min.js"></script>
<script src="<%= BASE_URL %>datafeeds/udf/dist/polyfills.js"></script>
<script src="<%= BASE_URL %>datafeeds/udf/dist/bundle.js"></script>
```
*components*
```
//    import { widget } from '@/charting_library.min';
……
    const tvWidget = new window.TradingView.widget(widgetOptions);
    // const tvWidget = new widget(widgetOptions);
    this.tvWidget = tvWidget;
```
