### ISSUE TITLE
./src/charting_library/charting_library.min.js no-unused-expressions with react-javascript

### ISSUE THREAD

**Issue by v4n8877** [tradingview/charting-library-examples#60]
Sorry, my english is bad, 
I try with example but i got an issue when import {widget} from '../../../../../charting_library/charting_library.min'. 
![error](https://user-images.githubusercontent.com/16847705/47420463-b111a000-d7a8-11e8-94de-8d1104a85dd5.png).
How can i fix an issue
thanks

**Comment by machy44** [comment]
I have the same issue.

**Comment by kirchet** [comment]
Try to do what is described [here ](https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104)

**Comment by machy44** [comment]
Thanks. I found tutorial [https://medium.com/@jonchurch/tradingview-charting-library-js-api-setup-for-crypto-part-1-57e37f5b3d5a](tradingview-charting-library-js-api-setup-for-crypto) He creates the trading view chart as a global variable [https://github.com/jonchurch/tradingview-js-api-tutorial/blob/master/part1/src/components/TVChartContainer/index.jsx](here)

**Comment by AlokPundir** [comment]
Hi getting error : Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function 

(anonymous function)
src/charting_library/charting_library.min.js:232
  229 |     i.addEventListener("load", e, !1);
  230 | })),
  231 | this._innerWindowLoaded.then(function () {
> 232 |     t._innerWindow().widgetReady(function () {
      | ^  233 |         t._ready = !0;
  234 |         for (var e = 0, o = t._readyHandlers; e < o.length; e++) {
  235 |             var i = o[e];

**Comment by nomanabid123** [comment]
how did you  fix this error

**Comment by nomanabid123** [comment]
src\charting_library\charting_library.esm.js
  Line 77:7:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 88:5:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 123:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 190:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 300:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 302:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 309:11:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 357:7:   Expected an assignment or function call and instead saw an expression  no-unused-expressions        
  Line 465:1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by timocov** [comment]
@nomanabid123 see https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104

**Comment by akshaynovostack** [comment]
mention /* eslint-disable */ at the top of the  charting_library.esm.js before the function starts
