### ISSUE TITLE
React TradingView deploy to production can't work 

### ISSUE THREAD

**Issue by kenneth** [tradingview/charting-library-examples#64]
`
TypeError: i.contentWindow.widgetReady is not a function. (In 'i.contentWindow.widgetReady(function(){t._ready=!0;for(var e=0,o=t._readyHandlers;e<o.length;e++){o[e].call(t)}i.contentWindow.initializationFinished()})', 'i.contentWindow.widgetReady' is undefined)
`

**Comment by timocov** [comment]
Did you search the similar issues before create this issue?

**Comment by timocov** [comment]
Duplicate of #15
