### ISSUE TITLE
Where are the charting library docs? 

### ISSUE THREAD

**Issue by clickbrain** [tradingview/charting-library-examples#65]
Sorry to bother in this area, but trying to find the documentation for the charting library and this is the only place in Github. Links on this page to Github docs are broken - https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library

**Describe the bug**

Getting 404s in Github for all the charting library docs linked on this page: 
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**To Reproduce**

Click the links for documentation on the TradingView library page. 

**Expected behavior**

See the docs

**Comment by ezhukovskiy** [comment]
You should sign the agreement first. Then you'll get access to the docs and the code.

**Comment by ezhukovskiy** [comment]
Click "download" - https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library

**Comment by clickbrain** [comment]
Ahh, thanks. Maybe put a note on that page so others will understand.
