### ISSUE TITLE
Missing API key for React JS production builds

### ISSUE THREAD

**Issue by coreycaplan3** [tradingview/charting-library-examples#67]
Is there an API key needed to run the chart in production? It seems to fail to load at runtime and complains about missing a key. I'm not sure where to get it though.

I'm happy to provide more information but I'm not sure what's most useful for the team to diagnose it.

**Comment by timocov** [comment]
I believe this issue should be opened here, not in charting library repo.

**Comment by timocov** [comment]
> Is there an API key needed to run the chart in production?

What do you mean?

>  It seems to fail to load at runtime and complains about missing a key. I'm not sure where to get it though.

Where do you get this errors? You can check https://charting-library.tradingview.com - we don't use any API key there.

**Comment by coreycaplan3** [comment]
I'll close the issue for now. Seems like our frontend developer misunderstood the error he was getting.
