### ISSUE TITLE
how to interval option change ?

### ISSUE THREAD

**Issue by neuralBC-M** [tradingview/charting-library-examples#83]
I plugged the library into [react] as I told you. However, the default interval options are [1day, 2day, 3day, 1week, 3week, 3weekks, 1month, 6months]. I'm trying to change this option, but I don't know what to do if I look at api and look for issues. Is there any way? Below is the re-exchange code.

`static defaultProps = {
    symbol: 'AAPL',
    supported_resolutions: [ '15', '30', '60', '120', '240', '720', '1D', '1W' ], has_intraday: true,
    interval: '1',
    seconds_multipliers: ["1S", "5S", "15S"],
    containerId: 'tv_chart_container',
    datafeedUrl: 'https://demo_feed.tradingview.com',
    libraryPath: '/charting_library/',
    chartsStorageUrl: 'https://saveload.tradingview.com',
    chartsStorageApiVersion: '1.12',
    clientId: 'tradingview.com',
    userId: 'public_user_id',
    fullscreen: false,
    autosize: true,
    intervals : ["D", "5D"],
    studiesOverrides: {},
  };

  tvWidget = null;

  componentDidMount() {
    const widgetOptions = {
      symbol: this.props.symbol,
      // BEWARE: no trailing slash is expected in feed URL
      datafeed: new window.Datafeeds.UDFCompatibleDatafeed(this.props.datafeedUrl),
      seconds_multipliers: this.props.seconds_multipliers,
      interval: this.props.interval,
      has_seconds: true,
      timezone: "Asia/Seoul",
      container_id: this.props.containerId,
      library_path: this.props.libraryPath,
      theme: "Dark"
      locale: getLanguageFromURL() || 'en',
      disabled_features: ['use_localstorage_for_settings'],
      has_weekly_and_monthly: false,
      enabled_features: ['study_templates'],
      charts_storage_url: this.props.chartsStorageUrl,
      charts_storage_api_version: this.props.chartsStorageApiVersion,
      client_id: this.props.clientId,
      user_id: this.props.userId,
      fullscreen: this.props.fullscreen,
      autosize: this.props.autosize,
      studies_overrides: this.props.studiesOverrides
    };

    const tvWidget = new widget(widgetOptions);
    this.tvWidget = tvWidget;

    tvWidget.onChartReady(() => {
      const button = tvWidget.createButton()
        .attr('title', 'Click to show a notification popup')
        .addClass('apply-common-tooltip')
        .on('click', () => tvWidget.showNoticeDialog({
          title: 'Notification',
          body: 'TradingView Charting Library API works correctly',
          callback: () => {
            console.log('Noticed!');
          },
        }));

      button[0].innerHTML = 'Check API';
    });
  }

  componentWillUnmount() {
    if (this.tvWidget !== null) {
      this.tvWidget.remove();
      this.tvWidget = null;
    }
  }`

my widget interval img
![2019-02-06 2 49 15](https://user-images.githubusercontent.com/46945885/52293329-e0e05e80-29b9-11e9-969f-fb482635b407.png)

want widget interval
![2019-02-06 2 49 31](https://user-images.githubusercontent.com/46945885/52293353-f190d480-29b9-11e9-9cff-376c93b39901.png)

**Comment by timocov** [comment]
Let's continue in https://github.com/tradingview/charting_library/issues/3751
