### ISSUE TITLE
Question regarding react app setup

### ISSUE THREAD

**Issue by amargautam** [tradingview/charting-library-examples#87]
I have some questions regarding react example.

1. I notice that you copied the charting_library folder in both public and src, may I know the reason for that?

2. If we are not using create-react-app, how do you suggest we bundle the library?

3. What does the `libraryPath` in `defaultProps` actually do?

**Comment by timocov** [comment]
Hi,

1. @everget can you please take a look?
1. In this case you need to bundle in your app only `charting_library.min.js` module, other files should be served as static files.
1. @everget

**Comment by everget** [comment]
@amargautam Hi,
1. This is due to the specifics of the `create-react-app` starter kit
3. Using `libraryPath` you can specify the path to the folder that contains Charting Library and its static assets

**Comment by amargautam** [comment]
Thank you. We solved this problem. We don't use creat react app so was kind of confused.

**Comment by timocov** [comment]
> We solved this problem

@amargautam so, can we close this issue for now?
