### ISSUE TITLE
React-native example

### ISSUE THREAD

**Issue by makedonsky94** [tradingview/charting-library-examples#89]
- **Framework/library: React-native**
- **Link to page with the framework/library: https://github.com/facebook/react-native**

**Comment by dinhtu0802** [comment]
Hi. How to import trandingview to react-native? 
Can you help me?

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/tree/master/react-native

**Comment by testn** [comment]
@timocov  Does it work with Android as well?

**Comment by timocov** [comment]
Afaik no, it doesn't work on Android. @makedonsky94 ?

**Comment by makedonsky94** [comment]
There was an [issue](https://github.com/react-native-community/react-native-webview/issues/560) in react-native library.
I guess we should check if it was fixed. But I see no response by react-native's developers. So maybe WebView still have that bug with iframe
