### ISSUE TITLE
Cannot read property 'UDFCompatibleDatafeed' of undefined in react-javascript

### ISSUE THREAD

**Issue by fintegri** [tradingview/charting-library-examples#92]
Cannot read property 'UDFCompatibleDatafeed' of undefined

error throw after run react project.please help me what should I do .

**Comment by timocov** [comment]
> please help me what should I do .

Let's start from what did you do already?

**Comment by fintegri** [comment]
I need step by step react javascript coding example sir ,I try many way but work anything so kindly provide example with package

**Comment by dosodiapraveen** [comment]
same problem 

const widgetOptions: ChartingLibraryWidgetOptions = {
            symbol: this._symbol,
            datafeed: new (window as any).Datafeeds.UDFCompatibleDatafeed(this._datafeedUrl),
            interval: this._interval,
            container_id: this._containerId,
            library_path: this._libraryPath,
            locale: getLanguageFromURL() || 'en',
            disabled_features: ['use_localstorage_for_settings'],
            enabled_features: ['study_templates'],
            charts_storage_url: this._chartsStorageUrl,
            charts_storage_api_version: this._chartsStorageApiVersion,
            client_id: this._clientId,
            user_id: this._userId,
            fullscreen: this._fullscreen,
            autosize: this._autosize,
        };


window dont have field Datafeeds

**Comment by fintegri** [comment]
Hi,

Please anyone help to fix my issue its emergency.Still can't able to integrate reactJS tradingview chart try many ways but not get anything.Please help to fix.

**Comment by fintegri** [comment]
@timocov 
What is the status ?
Could you please help me to rectify this issue?

**Comment by timocov** [comment]
Status is I waiting you for an answer on https://github.com/tradingview/charting-library-examples/issues/92#issuecomment-482630183.

**Comment by fintegri** [comment]
Issue fixed.
because I remove all typescript file in the charting library finally issue has been fixed

**Comment by imarun577** [comment]
please give your chart library

**Comment by sureshdas** [comment]
you have to add Bundle.js and Pollyfills.js in index.html file

After that the issue will solve

**Comment by LilCore** [comment]
> Issue fixed.
> because I remove all typescript file in the charting library finally issue has been fixed

What¿?

**Comment by moderniinfotech-123** [comment]
same problem on angular 7

const widgetOptions: ChartingLibraryWidgetOptions = {
symbol: this._symbol,
datafeed: new (window as any).Datafeeds.UDFCompatibleDatafeed(this._datafeedUrl),
interval: this._interval,
container_id: this._containerId,
library_path: this._libraryPath,
locale: getLanguageFromURL() || 'en',
disabled_features: ['use_localstorage_for_settings'],
enabled_features: ['study_templates'],
charts_storage_url: this._chartsStorageUrl,
charts_storage_api_version: this._chartsStorageApiVersion,
client_id: this._clientId,
user_id: this._userId,
fullscreen: this._fullscreen,
autosize: this._autosize,
};

window dont have field Datafeeds

**Comment by moderniinfotech-123** [comment]
add in index.html angular 8
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="/assets/datafeeds/udf/dist/polyfills.js"></script>
    <script src="/assets/datafeeds/udf/dist/bundle.js"></script>

**Comment by Fawaz456** [comment]
@moderniinfotech-123  Tried it still getting same error

ERROR TypeError: Cannot read property 'UDFCompatibleDatafeed' of undefined

**Comment by timocov** [comment]
@moderniinfotech-123 also you can import datafeeds instead of using datafeeds from global scope `datafeed: new (window as any).Datafeeds.UDFCompatibleDatafeed(this._datafeedUrl),`.

**Comment by bmilliren** [comment]
> @moderniinfotech-123 also you can import datafeeds instead of using datafeeds from global scope `datafeed: new (window as any).Datafeeds.UDFCompatibleDatafeed(this._datafeedUrl),`.

@timocov we are having the exact same issue and we are importing. I am loading both Bundle.js and Pollyfills.js into the index.html but we are still getting this error from the componentDidMount function. Appears that the datafeed is undefined. Any help would be much appreciated. We are trying to integrate the trading view within our application for technical analysis and have been struggling with this very issue for a month. 

Uncaught TypeError: Cannot read property 'UDFCompatibleDatafeed' of undefined
    at TVChartContainer.componentDidMount (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:29409:44)
    at commitLifeCycles (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:20084:22)
    at commitLayoutEffects (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:23073:7)
    at HTMLUnknownElement.callCallback (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:458:14)
    at Object.invokeGuardedCallbackDev (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:507:16)
    at invokeGuardedCallback (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:562:31)
    at commitRootImpl (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:22811:9)
    at unstable_runWithPriority (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:28411:12)
    at runWithPriority$1 (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:11309:10)
    at commitRoot (eval at <anonymous> (jquery-1.10.2.js:616), <anonymous>:22651:3)
reac

**Comment by chicky095** [comment]
Any update on this issue?

**Comment by premier213** [comment]
I still have this problem in next.js 11!

![image](https://user-images.githubusercontent.com/4321174/132086472-d5fc6ebd-0710-42db-9c92-a627cda26347.png)

**Comment by CompendiumFi** [comment]
TypeError: Cannot read properties of undefined (reading 'UDFCompatibleDatafeed') after building production react

**Comment by gtlackey** [comment]
Any update on this issue?

**Comment by lynn-hector** [comment]
I am also facing the same issue after building production vue.js, any update on this issue?

**Comment by romfrancois** [comment]
Are you guys experiencing this issue only when building production meaning it works locally?
Are you on the latest version of the examples?
Would it somehow be possible to inspect your branch/site by providing us with credentials?

**Comment by bi123co** [comment]
viewConfig.datafeed.onReady(res => {
      viewConfig.datafeed = new (window as any).Datafeeds.UDFCompatibleDatafeed(datafeedUrl)
      let tv = new widget(viewConfig)
      console.log(tv)
    })

I solved this problem by add  "viewConfig.datafeed.onReady", you can try it

**Comment by gredenko** [comment]
This issue is happening for me, with the error
'Uncaught TypeError: Datafeeds.UDFCompatibleDataFeed is not a constructor'

All scripts loaded, even added polyfills which was not in the tutorial.

**Comment by qf-team** [comment]
this doesn't work for me in Angular 17
