### ISSUE TITLE
Charting-Library Example (react-javascript) - Failed to Compile Error!

### ISSUE THREAD

**Issue by SavosRU** [tradingview/charting-library-examples#93]
Hi!
I try to run example with React-Javascript code.
And sure I read "how-to" ;-)

Command **"npm install"** was complete successfully. 
All need folders from charting-library was copied into "public" and "src" etc. 

But when I make **"npm start"** - I've got errors in the terminal and in the browser: 
```
./src/charting_library/charting_library.min.js
  Line 1:  'define' is not defined  no-undef

```
What I can to do with this situation???
Or what I MUST to do???

![image](https://user-images.githubusercontent.com/6779356/56090657-a90c0080-5ead-11e9-9c89-ce820c36a649.png)

![image](https://user-images.githubusercontent.com/6779356/56090650-998cb780-5ead-11e9-9d97-042b81039f51.png)

**Comment by iamkhan21** [comment]
Same story, man

**Comment by timocov** [comment]
https://github.com/tradingview/charting-library-examples/issues/36#issuecomment-411023104
