### ISSUE TITLE
Price decimal digits

### ISSUE THREAD

**Issue by muazcoban** [tradingview/charting-library-examples#95]
Hi,
How can I set 4 digits for decimal part?
![digit](https://user-images.githubusercontent.com/34477839/56287985-728cea80-6126-11e9-9a3b-41fc5566f89c.png)

**Comment by kirchet** [comment]
You should change `pricescale` in [symbol info](https://github.com/tradingview/charting_library/wiki/Symbology#minmov-pricescale-minmove2-fractional)
`pricescale = 10 ^ number of decimal places`
