### ISSUE TITLE
firt time render angular 7

### ISSUE THREAD

**Issue by 93Kamuran** [tradingview/charting-library-examples#96]
Hi,
I'm working on implement tradingview charts on my project. (angular 7) I followed steps and everything has gone well. Then I realized that if I stopped the serving project from Localhost and serve again my chart component closes and throw me to the login page. I think is a cause of rendering because If ı change chart component with another component in routing module and when the project running Then I change again component with chart components and i refresh page chart is rendered like a charm . I'm really confused about this situation

**Comment by elukonina** [comment]
Duplicate of #https://github.com/tradingview/charting_library/issues/3932

**Comment by kirchet** [comment]
Sorry for misundestanding, this issue should not be closed.
@93Kamuran, please provide a link to your chart and we'll take a look what is wrong.

**Comment by 93Kamuran** [comment]
> Sorry for misundestanding, this issue should not be closed.
> @93Kamuran, please provide a link to your chart and we'll take a look what is wrong.
It was all about my local storage. so it was my mistake. I solved the problem. Thank you for response

**Comment by kirchet** [comment]
You're welcome
