### ISSUE TITLE
how to show the watchlist

### ISSUE THREAD

**Issue by yuanjiacheng** [tradingview/charting-library-examples#98]
**Checklist**

- [ ] This issue is **NOT** related to the charting library itself

**Describe the bug**

**To Reproduce**

1. Clone the repo
2. Go to '....' folder
3. Run command

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yuanjiacheng** [comment]
I set the widgetbar in the widget as the doc said,but not work
![微信截图_20190424114759](https://user-images.githubusercontent.com/7556989/56631230-01e65080-6687-11e9-8a5e-04f80470c2c8.png)
![微信截图_20190424114836](https://user-images.githubusercontent.com/7556989/56631237-07439b00-6687-11e9-9ef4-722781adcbc4.png)

**Comment by kirchet** [comment]
Watch list is available only in [the trading terminal](tradingview trading terminal)
