### ISSUE TITLE
[react-javascript] TypeError: e._innerWindow(...).widgetReady is not a function when build

### ISSUE THREAD

**Issue by CorentinGC** [tradingview/charting-library-examples#99]
Hi ! 

All is working in dev mode, but when I build the project, there is a TypeError and charting_library is not working.

How to reproduce:
1 - Clone the repo
2 - Put charting_library + datafeeds in `/public` and charting_library in `/src`
3 - Do `npm start` then serve : Everything is ok.
4 - do `npm run build` and serve app : 
```
Uncaught (in promise) TypeError: e._innerWindow(...).widgetReady is not a function
    at charting_library.min.js:2
charting_library.min.js:2 Uncaught (in promise) TypeError: e._innerWindow(...).widgetReady is not a function
    at charting_library.min.js:2

```

**Comment by savitar-dev** [comment]
Ok, after some search, I "fixed" it.
 Just run `serve` without `-s` parameter, or with another serveur ( like python ) as explained here: https://github.com/tradingview/charting-library-examples/issues/15#issuecomment-411001758

**Comment by CorentinGC** [comment]
Ok, after some search, I "fixed" it.
 Just run `serve` without `-s` parameter, or with another serveur ( like python ) as explained here: https://github.com/tradingview/charting-library-examples/issues/15#issuecomment-411001758

**Comment by brandoncollins7** [comment]
This does not fix the issue. -s is required for the router to be able to select the correct page...

**Comment by creed-victor** [comment]
@timocov as said in the comment above, suggested solution is not a fix - only works for pages that have one page

**Comment by vish2595** [comment]
Getting same.

**Comment by Abolfazl2647** [comment]
i face this issue and i had a repo like this.
`
/public -> tradingview lib here
/src
/dist
`
when i try to serve -s dist browser redirect the charting_library but when is serve the whole project , click and choose the dist folder it just works fine.
i think when you serve the dist folder the server have no idea to deal with the public folder which tradingview library is in it.


but when  i try to use tradingview in react project (CRA) a same problem pops up with `charting_library.ems.js` file  and said 
`
Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function -- on line 8
`

any ideas ?
